import {competencyDefinitions,type CompetencyCode,type AssessmentQuestionType}from "@/constants/methodology";
import {methodologyItems}from "@/constants/methodology-items";
import type { Difficulty, Question, SkillCategory } from "@/types/domain";

type LegacyType="multiple-choice"|"code-reading"|"logic"|"scenario";
type Seed = [SkillCategory, Difficulty, LegacyType, string, string, string[], string[], number];
const seeds: Seed[] = [
  ["digital-literacy","easy","multiple-choice","Which file name is easiest to find later?","Qaysi fayl nomini keyin topish oson?",["document1.docx","Grade9_Biology_Lab_2026.docx","new-final-last.docx","scan0001.docx"],["hujjat1.docx","9Sinf_Biologiya_Lab_2026.docx","yangi-oxirgi.docx","scan0001.docx"],1],
  ["digital-literacy","easy","scenario","You need to collaborate on a report. What is the best approach?","Hisobotni hamkorlikda tayyorlash uchun eng yaxshi usul qaysi?",["Email a new copy after every edit","Use a shared document with permissions","Send screenshots","Let everyone use one password"],["Har tahrirdan keyin yangi nusxa yuborish","Ruxsatli umumiy hujjatdan foydalanish","Skrinshot yuborish","Hamma bitta paroldan foydalanishi"],1],
  ["digital-literacy","medium","scenario","A surprising statistic has no source. What should you do first?","Manbasiz hayratlanarli statistika ko‘rdingiz. Avval nima qilasiz?",["Share it quickly","Check the claim in reliable independent sources","Trust it if it has many likes","Ask AI and accept its answer"],["Tez ulashish","Ishonchli mustaqil manbalarda tekshirish","Layklar ko‘p bo‘lsa ishonish","SIdan so‘rab javobini qabul qilish"],1],
  ["digital-literacy","medium","multiple-choice","What does a spreadsheet formula normally begin with?","Elektron jadval formulasi odatda nima bilan boshlanadi?",["#","=","@","&"],["#","=","@","&"],1],
  ["digital-literacy","medium","scenario","Your cloud storage is full. What is the most useful first step?","Bulut xotirasi to‘ldi. Eng foydali birinchi qadam?",["Create another account","Review storage by file size and remove duplicates","Delete random files","Turn off device security"],["Yangi hisob ochish","Hajm bo‘yicha tekshirib, nusxalarni o‘chirish","Tasodifiy fayllarni o‘chirish","Qurilma himoyasini o‘chirish"],1],
  ["digital-literacy","hard","logic","Which search query is most precise for an official 2025 school internet report in Uzbekistan?","O‘zbekistondagi 2025 maktab interneti rasmiy hisobotini topish uchun eng aniq so‘rov?",["internet schools","Uzbekistan school internet report 2025 site:gov.uz filetype:pdf","good internet report","2025 PDF"],["maktab internet","O‘zbekiston maktab internet hisoboti 2025 site:gov.uz filetype:pdf","yaxshi internet hisoboti","2025 PDF"],1],
  ["digital-literacy","hard","scenario","A chart starts its vertical axis at 95 instead of 0. What risk does this create?","Diagramma vertikal o‘qi 0 emas, 95 dan boshlangan. Bu qanday xavf tug‘diradi?",["Smaller file size","Differences may look much larger than they are","Labels become multilingual","Data becomes private"],["Fayl kichrayadi","Farqlar aslidan ancha katta ko‘rinadi","Yozuvlar ko‘p tilli bo‘ladi","Ma’lumot maxfiylashadi"],1],
  ["digital-literacy","hard","scenario","Which action best preserves a final report and its editing history?","Yakuniy hisobot va tahrir tarixini eng yaxshi nima saqlaydi?",["Overwrite the only local file","Use version history and export a dated PDF","Photograph the screen","Rename it final-final"],["Yagona mahalliy fayl ustiga yozish","Versiya tarixi va sanali PDF eksport","Ekranni suratga olish","final-final deb nomlash"],1],

  ["computational-thinking","easy","logic","What is the first step when solving a large problem?","Katta muammoni yechishda birinchi qadam nima?",["Guess an answer","Break it into smaller parts","Write code immediately","Ignore constraints"],["Javobni taxmin qilish","Kichik qismlarga ajratish","Darhol kod yozish","Cheklovlarni e’tiborsiz qoldirish"],1],
  ["computational-thinking","easy","logic","What comes next: 2, 4, 8, 16, …?","Keyingi son: 2, 4, 8, 16, …?",["18","24","32","64"],["18","24","32","64"],2],
  ["computational-thinking","medium","logic","A robot repeats: move 2 steps, turn right. How many turns make a square?","Robot 2 qadam yurib, o‘ngga buriladi. Kvadrat uchun nechta burilish kerak?",["2","3","4","6"],["2","3","4","6"],2],
  ["computational-thinking","medium","scenario","Which is an example of abstraction?","Abstraksiyaga qaysi misol mos?",["Copying every detail","A metro map showing lines but not every building","Trying random answers","Making a file larger"],["Har bir tafsilotni ko‘chirish","Barcha binolarsiz metro yo‘llari xaritasi","Tasodifiy javob sinash","Faylni kattalashtirish"],1],
  ["computational-thinking","medium","logic","If all coded files are encrypted and report.csv is not encrypted, what can you conclude?","Barcha kodlangan fayllar shifrlangan, report.csv shifrlanmagan. Xulosa?",["It is definitely coded","It is not a coded file","It contains no data","It is a virus"],["Albatta kodlangan","Kodlangan fayl emas","Ma’lumot yo‘q","Virus"],1],
  ["computational-thinking","hard","logic","Binary search works correctly only when the list is…","Ikkilik qidiruv to‘g‘ri ishlashi uchun ro‘yxat…",["random","sorted","duplicated","hidden"],["tasodifiy","saralangan","takrorlangan","yashirin"],1],
  ["computational-thinking","hard","logic","A process takes 3 minutes per item. With 2 workers operating independently, 10 items take at least…","Har element 3 daqiqa. 2 mustaqil ishchi 10 elementni kamida…",["10 minutes","15 minutes","20 minutes","30 minutes"],["10 daqiqa","15 daqiqa","20 daqiqa","30 daqiqa"],1],
  ["computational-thinking","hard","scenario","A solution works for 5 test cases but fails on empty input. What was missing?","Yechim 5 sinovda ishladi, bo‘sh kiritishda xato berdi. Nima yetishmadi?",["A louder alert","An edge-case test","More colors","A longer variable name"],["Balandroq ogohlantirish","Chegaraviy holat sinovi","Ko‘proq rang","Uzunroq o‘zgaruvchi nomi"],1],

  ["programming","easy","code-reading","What is printed by: x = 3; print(x + 2)?","x = 3; print(x + 2) nima chiqaradi?",["2","3","5","32"],["2","3","5","32"],2],
  ["programming","easy","multiple-choice","Which construct repeats instructions?","Qaysi tuzilma ko‘rsatmalarni takrorlaydi?",["Variable","Loop","Comment","String"],["O‘zgaruvchi","Sikl","Izoh","Satr"],1],
  ["programming","medium","code-reading","What is printed by: for i in range(3): print(i)?","for i in range(3): print(i) nima chiqaradi?",["1,2,3","0,1,2","0,1,2,3","3 only"],["1,2,3","0,1,2","0,1,2,3","Faqat 3"],1],
  ["programming","medium","code-reading","If score = 70, which condition is true?","score = 70 bo‘lsa qaysi shart rost?",["score < 50","score == 7","score >= 60","score > 100"],["score < 50","score == 7","score >= 60","score > 100"],2],
  ["programming","medium","multiple-choice","What is a function mainly used for?","Funksiya asosan nima uchun ishlatiladi?",["Reusable named behavior","Changing screen brightness","Storing only images","Connecting power"],["Qayta ishlatiladigan nomli amal","Ekran yorqinligini o‘zgartirish","Faqat rasm saqlash","Quvvat ulash"],0],
  ["programming","hard","code-reading","What is len([4, 7, 9, 2])?","len([4, 7, 9, 2]) natijasi?",["2","4","9","22"],["2","4","9","22"],1],
  ["programming","hard","code-reading","After x=5; x=x*2; x=x-3, x equals…","x=5; x=x*2; x=x-3 dan keyin x…",["2","5","7","10"],["2","5","7","10"],2],
  ["programming","hard","scenario","A program crashes when dividing by user input. Best fix?","Dastur foydalanuvchi kiritgan songa bo‘lishda to‘xtaydi. Eng yaxshi yechim?",["Hide the error","Validate input and handle zero","Repeat the division","Remove all input"],["Xatoni yashirish","Kiritishni tekshirish va nolni qayta ishlash","Bo‘lishni takrorlash","Barcha kiritishni olib tashlash"],1],

  ["cybersecurity","easy","scenario","Which password is strongest?","Qaysi parol kuchliroq?",["azamat123","password","T0sh!River-Cloud7","2009birthday"],["azamat123","password","T0sh!River-Cloud7","2009tugilgan"],2],
  ["cybersecurity","easy","scenario","A stranger asks for your verification code. You should…","Begona tasdiqlash kodini so‘radi. Siz…",["Send it once","Never share it","Post it publicly","Ask for their password"],["Bir marta yuborasiz","Hech qachon bermaysiz","Ommaga yozasiz","Uning parolini so‘raysiz"],1],
  ["cybersecurity","medium","scenario","An email says your account closes in 10 minutes and links to login. First action?","Xat hisob 10 daqiqada yopilishini aytib, kirish havolasini berdi. Birinchi amal?",["Click quickly","Open the official site separately and verify","Reply with password","Forward to everyone"],["Tez bosish","Rasmiy saytni alohida ochib tekshirish","Parol bilan javob berish","Hammaga yuborish"],1],
  ["cybersecurity","medium","multiple-choice","What does multi-factor authentication add?","Ko‘p bosqichli tasdiqlash nima qo‘shadi?",["A second independent verification step","A shorter password","Public access","Faster viruses"],["Ikkinchi mustaqil tekshiruv bosqichi","Qisqaroq parol","Ommaviy kirish","Tezroq virus"],0],
  ["cybersecurity","medium","scenario","On public Wi-Fi, which task is riskiest?","Ommaviy Wi-Fi da qaysi ish xavfliroq?",["Reading saved notes","Online banking without protection","Viewing a downloaded photo","Using calculator"],["Saqlangan yozuvni o‘qish","Himoyasiz internet-banking","Yuklangan rasmni ko‘rish","Kalkulyator ishlatish"],1],
  ["cybersecurity","hard","scenario","You installed an unknown attachment and the device acts strangely. What next?","Noma’lum ilova o‘rnatildi va qurilma g‘alati ishlayapti. Keyin nima?",["Ignore it","Disconnect network and report/scan","Send the file to friends","Disable updates forever"],["E’tibor bermaslik","Tarmoqdan uzib, xabar berish/tekshirish","Faylni do‘stlarga yuborish","Yangilanishni doimiy o‘chirish"],1],
  ["cybersecurity","hard","multiple-choice","Why are software updates security-relevant?","Dastur yangilanishlari nega xavfsizlik uchun muhim?",["They only change colors","They often patch known vulnerabilities","They publish passwords","They remove encryption"],["Faqat rangni o‘zgartiradi","Ma’lum zaifliklarni tuzatadi","Parollarni e’lon qiladi","Shifrlashni olib tashlaydi"],1],
  ["cybersecurity","hard","scenario","What is the safest backup approach for important schoolwork?","Muhim maktab ishini zaxiralashning eng xavfsiz usuli?",["One copy on one device","Multiple copies, including one separate location","Only in downloads","Send to an unknown chat"],["Bir qurilmada bitta nusxa","Bir nechta nusxa, bittasi alohida joyda","Faqat yuklamalarda","Noma’lum chatga yuborish"],1],

  ["ai-literacy","easy","multiple-choice","Generative AI usually produces answers by…","Generativ SI odatda javobni qanday yaratadi?",["Predicting patterns from training data","Reading minds","Always searching live official data","Proving every sentence"],["O‘rgatilgan ma’lumot naqshlarini bashorat qilish","Fikr o‘qish","Doim jonli rasmiy ma’lumot qidirish","Har gapni isbotlash"],0],
  ["ai-literacy","easy","scenario","AI gives a confident historical date. What should you do?","SI tarixiy sanani ishonch bilan berdi. Nima qilish kerak?",["Assume it is correct","Verify with reliable sources","Add more confidence","Hide the source"],["To‘g‘ri deb bilish","Ishonchli manbada tekshirish","Ishonchni oshirish","Manbani yashirish"],1],
  ["ai-literacy","medium","multiple-choice","An AI hallucination is…","SI gallyutsinatsiyasi nima?",["A hardware upgrade","A plausible but false generated claim","A secure password","A compressed image"],["Qurilma yangilanishi","Ishonarli ko‘ringan, ammo noto‘g‘ri da’vo","Xavfsiz parol","Siqilgan rasm"],1],
  ["ai-literacy","medium","scenario","Which data should not be pasted into a public AI tool?","Ommaviy SI vositasiga qaysi ma’lumot kiritilmasligi kerak?",["A public poem title","A private student record","A general math question","A fictional name"],["Ommaviy she’r nomi","O‘quvchining maxfiy ma’lumoti","Umumiy matematika savoli","To‘qima ism"],1],
  ["ai-literacy","medium","scenario","Two groups receive systematically different AI outcomes. What should be examined?","Ikki guruh doimiy ravishda turli SI natija oldi. Nimani tekshirish kerak?",["Screen size","Bias in data and system design","Keyboard color","Internet logo"],["Ekran hajmi","Ma’lumot va tizim dizaynidagi og‘ish","Klaviatura rangi","Internet logosi"],1],
  ["ai-literacy","hard","scenario","Best way to use AI for an essay assignment?","Insho vazifasida SIdan eng yaxshi foydalanish?",["Submit raw output","Use it for ideas, verify claims, and write your own work per rules","Ask it to invent citations","Hide all usage"],["Tayyor javobni topshirish","G‘oya olish, da’volarni tekshirish va qoidalarga ko‘ra o‘zi yozish","Soxta manba yaratish","Foydalanishni yashirish"],1],
  ["ai-literacy","hard","multiple-choice","Why can changing a prompt change the answer?","Nega so‘rov o‘zgarishi javobni o‘zgartiradi?",["The model uses context and wording","The battery becomes stronger","Facts change instantly","The internet restarts"],["Model kontekst va ifodadan foydalanadi","Batareya kuchayadi","Faktlar darhol o‘zgaradi","Internet qayta boshlanadi"],0],
  ["ai-literacy","hard","scenario","A medical AI suggestion conflicts with a qualified doctor. Best response?","SI tibbiy tavsiyasi malakali shifokorga zid. Eng yaxshi yo‘l?",["Follow AI secretly","Seek qualified professional clarification; do not self-treat","Mix both medicines","Post personal data publicly"],["Yashirincha SIga amal qilish","Malakali mutaxassisdan aniqlik olish, o‘zini davolamaslik","Dorilarni aralashtirish","Shaxsiy ma’lumotni e’lon qilish"],1],

  ["problem-solving","easy","scenario","Before proposing a solution, you should first…","Yechim taklif qilishdan oldin…",["Define the problem clearly","Buy software","Blame someone","Choose the prettiest idea"],["Muammoni aniq belgilash","Dastur sotib olish","Kimnidir ayblash","Eng chiroyli g‘oyani tanlash"],0],
  ["problem-solving","easy","logic","You have 3 possible routes. How should you choose?","3 ta yo‘l bor. Qanday tanlaysiz?",["Always first","Compare relevant criteria such as time and safety","Randomly","Choose the longest"],["Doim birinchisi","Vaqt va xavfsizlik kabi mezonlarni solishtirish","Tasodifiy","Eng uzuni"],1],
  ["problem-solving","medium","scenario","Students often miss announcements. What is the best first research step?","O‘quvchilar e’lonlarni ko‘p o‘tkazib yuboradi. Birinchi tadqiqot qadami?",["Build an app immediately","Ask students when and why they miss them","Print more without checking","Remove announcements"],["Darhol ilova yaratish","Qachon va nega o‘tkazib yuborishini so‘rash","Tekshirmay ko‘proq chop etish","E’lonlarni olib tashlash"],1],
  ["problem-solving","medium","scenario","A prototype fails. What is the most productive response?","Prototip ishlamadi. Eng samarali javob?",["Hide the result","Use evidence to revise and test again","Never retry","Change the goal after every test"],["Natijani yashirish","Dalil asosida tuzatib, qayta sinash","Qayta urinmaslik","Har sinovda maqsadni o‘zgartirish"],1],
  ["problem-solving","medium","logic","Which measure best shows a queue solution worked?","Navbat yechimi ishlaganini nima yaxshi ko‘rsatadi?",["Logo color","Average waiting time before and after","Number of posters","Developer age"],["Logo rangi","Oldin va keyingi o‘rtacha kutish vaqti","Plakat soni","Dasturchi yoshi"],1],
  ["problem-solving","hard","scenario","A cheap solution helps many users but excludes students without smartphones. What should you do?","Arzon yechim ko‘pchilikka yordam beradi, ammo telefonsizlarni chetlatadi. Nima qilasiz?",["Ignore them","Add an accessible alternative and test both","Cancel all work","Hide the limitation"],["E’tibor bermaslik","Muqobil imkoniyat qo‘shib, ikkalasini sinash","Hammasini bekor qilish","Cheklovni yashirish"],1],
  ["problem-solving","hard","logic","A test score rose after a new program, but tutoring also increased. What is true?","Yangi dasturdan keyin ball oshdi, lekin repetitorlik ham ko‘paydi. To‘g‘ri xulosa?",["The program definitely caused it","Tutoring is a possible confounding factor","Scores are useless","Both had no effect"],["Albatta dastur sabab","Repetitorlik aralash omil bo‘lishi mumkin","Ball foydasiz","Ikkalasi ta’sirsiz"],1],
  ["problem-solving","hard","scenario","Two solutions score equally on impact. One costs half as much. Which criterion helps decide?","Ikki yechim ta’sir bo‘yicha teng, biri ikki baravar arzon. Qaysi mezon yordam beradi?",["Feasibility and cost-effectiveness","Font choice","Who spoke first","Number of slides"],["Amalga oshirish va xarajat samaradorligi","Shrift tanlovi","Kim birinchi gapirgani","Slayd soni"],0],
];

const typeExplanations = { en: "The selected answer reflects the safest and most effective practice.", uz: "Tanlangan javob eng xavfsiz va samarali amaliyotni aks ettiradi." };
const competencyRotation:Record<SkillCategory,CompetencyCode[]>={
  "digital-literacy":["DL-03","DL-04","DL-02","DL-03","DL-05","DL-01","DL-02","DL-04"],
  "computational-thinking":["CT-01","CT-02","CT-04","CT-03","CT-03","CT-04","CT-05","CT-05"],
  programming:["PF-01","PF-03","PF-03","PF-02","PF-04","PF-05","PF-01","PF-06"],
  cybersecurity:["CS-02","CS-02","CS-01","CS-02","CS-03","CS-05","CS-05","CS-05"],
  "ai-literacy":["AI-04","AI-02","AI-02","AI-05","AI-03","AI-05","AI-01","AI-05"],
  "problem-solving":["PS-02","PS-01","PS-02","PS-02","PS-01","PS-01","PS-01","PS-03"],
};
const typeMap:Record<LegacyType,AssessmentQuestionType>={"multiple-choice":"single-choice","code-reading":"code-reading",logic:"logic",scenario:"real-life-scenario"};
const categoryOffsets:Record<SkillCategory,number>={"digital-literacy":0,"computational-thinking":8,programming:16,cybersecurity:24,"ai-literacy":32,"problem-solving":40};
export const legacyQuestions: Question[] = seeds.map((seed,index) => {
  const [category,difficulty,type,enPrompt,uzPrompt,enOptions,uzOptions,correct] = seed;
  const categoryIndex=index-categoryOffsets[category];const competencyCode=competencyRotation[category][categoryIndex];const competency=competencyDefinitions[competencyCode];const id=`SKM-${competencyCode.slice(0,2)}-${difficulty.toUpperCase()}-${String(categoryIndex+101).padStart(3,"0")}`;const correctOptionId=String(correct);
  const requiresReview=difficulty==="medium"?categoryIndex===4:difficulty==="hard"?(category==="ai-literacy"?categoryIndex===7:category==="problem-solving"?categoryIndex===6:categoryIndex>=6):false;
  const reviewNotes=requiresReview?[difficulty==="medium"?"Legacy item held for educator review: distractor quality and roadmap usefulness need confirmation.":"Legacy item held for educator review: difficulty calibration and concept overlap need confirmation."]:[];
  return {id,version:1,status:"active",reviewStatus:requiresReview?"needs_review" as const:"approved" as const,reviewNotes,category,competencyCode,competencyName:competency.name,difficulty,type:typeMap[type],estimatedTimeSeconds:difficulty==="easy"?45:difficulty==="medium"?75:90,learningObjective:{en:`Apply ${competency.name} in a practical context.`,uz:`${competency.name} ko‘nikmasini amaliy vaziyatda qo‘llash.`},roadmapSkillMapping:competency.module,misconceptionId:`${competencyCode}-LEGACY`,misconceptionDescription:{en:`Needs support with ${competency.name}.`,uz:`${competency.name} bo‘yicha qo‘shimcha yordam kerak.`},tags:[category,competencyCode.toLowerCase(),type],prompt:{en:enPrompt,uz:uzPrompt},options:enOptions.map((label,optionIndex)=>({id:String(optionIndex),label:{en:label,uz:uzOptions[optionIndex]}})),correctAnswer:correctOptionId,correctOptionId,explanation:typeExplanations,publishable:!requiresReview};
});
export const questions:Question[]=[...methodologyItems.map(item=>{const ready=item.publishable;return{...item,reviewStatus:ready?"approved" as const:"do_not_publish" as const,reviewNotes:ready?[]:["Native matching or ranking interaction is not pilot-ready."]}}),...legacyQuestions];
