import { Download } from "lucide-react";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/dictionaries";
const exports=[
  ["participants","Anonymous participants","Anonim ishtirokchilar","Participant code, grade, location, access context, language, and consent metadata.","Ishtirokchi kodi, sinf, hudud, imkoniyat, til va rozilik metama’lumoti."],
  ["answers","Answer-level responses","Javoblar darajasidagi ma’lumot","Question version, selected response, response time, fractional score, and rapid flag.","Savol versiyasi, tanlangan javob, vaqt, ulushli ball va tez javob belgisi."],
  ["scores","Competency scores","Kompetensiya ballari","Anonymous participant competency scores, earned points, and coverage counts.","Anonim kompetensiya ballari, yig‘ilgan ball va qamrov sonlari."],
  ["questions","Question metadata","Savol metama’lumoti","Versioned bilingual question metadata without participant records.","Ishtirokchi yozuvlarisiz versiyalangan ikki tilli savol metama’lumoti."],
  ["misconceptions","Misconception summary","Noto‘g‘ri tushunchalar xulosasi","Anonymous misconception flags, occurrence counts, and priority.","Anonim noto‘g‘ri tushuncha belgilari, takrorlanish soni va ustuvorlik."],
] as const;
export default async function ExportsPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const uz=locale==="uz";return <div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{uz?"Himoyalangan ma’lumot olish":"Protected data access"}</p><h1 className="mt-1 text-2xl font-bold">{uz?"Eksportlar":"Exports"}</h1><p className="mt-1 text-sm text-slate-600">{uz?"Barcha fayllar UTF-8 CSV formatida va faqat administratorlar uchun.":"All files are UTF-8 CSV and require an authorized admin session."}</p><div className="mt-5 divide-y divide-slate-200 rounded-lg border border-slate-300 bg-white">{exports.map(([dataset,enTitle,uzTitle,enBody,uzBody])=><section key={dataset} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">{uz?uzTitle:enTitle}</h2><p className="mt-1 text-sm text-slate-600">{uz?uzBody:enBody}</p></div><a href={`/api/exports/${dataset}`} className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-md border border-slate-300 bg-white px-4 text-sm font-semibold hover:bg-slate-100"><Download size={16}/>{uz?"CSV yuklash":"Download CSV"}</a></section>)}</div></div>}
