import Link from "next/link";
import { Map, Menu } from "lucide-react";
import type { Dictionary } from "@/lib/i18n/dictionaries";
import type { Locale } from "@/types/domain";
import { ButtonLink } from "@/components/ui/button";

export function SiteHeader({locale,d}:{locale:Locale;d:Dictionary}) {
  const other=locale==="en"?"uz":"en";
  const links=[[`/${locale}/assessment`,d.nav.assessment],[`/${locale}/research`,d.nav.research],[`/${locale}#about`,d.nav.about]];
  return <header className="no-print sticky top-0 z-40 border-b border-ui-border bg-page/95 backdrop-blur"><div className="container-shell relative flex min-h-18 items-center justify-between gap-2 py-2"><Link href={`/${locale}`} className="flex min-w-0 items-center gap-2 rounded-lg font-extrabold text-ink sm:gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-teal-800 text-white"><Map size={19}/></span><span className="truncate">SkillMap <span className="hidden text-teal-800 sm:inline">Uzbekistan</span></span></Link><nav className="hidden items-center gap-3 text-sm font-semibold text-secondary-text lg:flex">{links.map(([href,label])=><Link key={href} className="rounded-md px-3 py-2 hover:bg-slate-100 hover:text-primary-text" href={href}>{label}</Link>)}</nav><div className="flex shrink-0 items-center gap-1 sm:gap-2"><Link aria-label={locale==="en"?"Switch to Uzbek":"Ingliz tiliga o‘tish"} className="rounded-md border border-transparent px-2.5 py-2 text-sm font-bold uppercase text-teal-900 hover:border-teal-300 hover:bg-teal-50" href={`/${other}`}>{other}</Link><ButtonLink href={`/${locale}/sign-in`} variant="secondary" className="hidden sm:inline-flex">{d.nav.signIn}</ButtonLink><details className="group lg:hidden"><summary aria-label={locale==="uz"?"Menyuni ochish":"Open menu"} className="grid size-10 cursor-pointer list-none place-items-center rounded-lg border border-ui-border bg-surface text-primary-text hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"><Menu size={20}/></summary><nav className="absolute inset-x-4 top-[calc(100%-2px)] rounded-xl border border-ui-border bg-white p-2 shadow-lg">{links.map(([href,label])=><Link key={href} className="block rounded-lg px-4 py-3 text-sm font-semibold text-primary-text hover:bg-slate-100" href={href}>{label}</Link>)}<Link className="block rounded-lg px-4 py-3 text-sm font-semibold text-primary-text hover:bg-slate-100 sm:hidden" href={`/${locale}/sign-in`}>{d.nav.signIn}</Link></nav></details></div></div></header>;
}
