import Link from "next/link";
import {BookOpenCheck,ChevronDown,LogOut,Map,Menu,Route,UserCircle} from "lucide-react";
import type {Dictionary} from "@/lib/i18n/dictionaries";
import type {Locale} from "@/types/domain";
import {ButtonLink} from "@/components/ui/button";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {signOutAction} from "@/actions/auth";

export async function SiteHeader({locale,d}:{locale:Locale;d:Dictionary}){
  const other=locale==="en"?"uz":"en",uz=locale==="uz";
  const links=[[`/${locale}/assessment`,d.nav.assessment],[`/${locale}/roadmap`,uz?"Yo‘l xaritasi":"Roadmap"],[`/${locale}/research`,d.nav.research],[`/${locale}#about`,d.nav.about]];
  const supabase=await createSupabaseServerClient();
  const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};
  const email=user?.email??"",displayName=typeof user?.user_metadata?.full_name==="string"?user.user_metadata.full_name:email.split("@")[0],initial=(displayName||email||"U").slice(0,1).toUpperCase();
  const profile=user?<details className="group relative"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-xl border border-ui-border bg-white px-2.5 py-1.5 text-sm font-bold hover:border-teal-400 hover:bg-teal-50"><span className="grid size-8 place-items-center rounded-full bg-teal-800 text-white" aria-hidden>{initial}</span><span className="hidden max-w-32 truncate md:block">{displayName}</span><ChevronDown size={15} className="transition group-open:rotate-180"/></summary><div className="absolute right-0 top-[calc(100%+.6rem)] w-72 overflow-hidden rounded-2xl border border-ui-border bg-white shadow-xl"><div className="border-b border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-teal-800 text-lg font-bold text-white">{initial}</span><div className="min-w-0"><strong className="block truncate">{displayName}</strong><span className="block truncate text-xs text-slate-600">{email}</span></div></div><span className="mt-3 inline-flex rounded-full bg-green-100 px-2.5 py-1 text-xs font-bold text-green-800">{uz?"Tizimga kirilgan":"Signed in"}</span></div><nav className="p-2"><Link href={`/${locale}`} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-slate-100"><UserCircle size={18}/>{uz?"Mening sahifam":"My dashboard"}</Link><Link href={`/${locale}/results`} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-slate-100"><BookOpenCheck size={18}/>{uz?"Natijalarim":"My results"}</Link><Link href={`/${locale}/roadmap`} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-slate-100"><Route size={18}/>{uz?"O‘quv rejam":"My learning plan"}</Link></nav><form action={signOutAction.bind(null,locale)} className="border-t border-slate-200 p-2"><button className="flex min-h-10 w-full items-center gap-3 rounded-lg px-3 text-sm font-semibold text-red-700 hover:bg-red-50"><LogOut size={18}/>{uz?"Chiqish":"Sign out"}</button></form></div></details>:<ButtonLink href={`/${locale}/sign-in`} variant="secondary" className="hidden sm:inline-flex">{d.nav.signIn}</ButtonLink>;
  return <header className="no-print sticky top-0 z-40 border-b border-ui-border bg-page/95 backdrop-blur"><div className="container-shell relative flex min-h-18 items-center justify-between gap-2 py-2"><Link href={`/${locale}`} className="flex min-w-0 items-center gap-2 rounded-lg font-extrabold text-ink sm:gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-teal-800 text-white"><Map size={19}/></span><span className="truncate">SkillMap <span className="hidden text-teal-800 sm:inline">Uzbekistan</span></span></Link><nav className="hidden items-center gap-3 text-sm font-semibold text-secondary-text lg:flex">{links.map(([href,label])=><Link key={href} className="rounded-md px-3 py-2 hover:bg-slate-100 hover:text-primary-text" href={href}>{label}</Link>)}</nav><div className="flex shrink-0 items-center gap-1 sm:gap-2"><Link aria-label={locale==="en"?"Switch to Uzbek":"Ingliz tiliga o‘tish"} className="rounded-md border border-transparent px-2.5 py-2 text-sm font-bold uppercase text-teal-900 hover:border-teal-300 hover:bg-teal-50" href={`/${other}`}>{other}</Link>{profile}<details className="group lg:hidden"><summary aria-label={uz?"Menyuni ochish":"Open menu"} className="grid size-10 cursor-pointer list-none place-items-center rounded-lg border border-ui-border bg-surface text-primary-text hover:bg-slate-100"><Menu size={20}/></summary><nav className="absolute inset-x-4 top-[calc(100%-2px)] rounded-xl border border-ui-border bg-white p-2 shadow-lg">{links.map(([href,label])=><Link key={href} className="block rounded-lg px-4 py-3 text-sm font-semibold hover:bg-slate-100" href={href}>{label}</Link>)}{!user&&<Link className="block rounded-lg px-4 py-3 text-sm font-semibold hover:bg-slate-100 sm:hidden" href={`/${locale}/sign-in`}>{d.nav.signIn}</Link>}</nav></details></div></div></header>;
}
