"use client";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, MapPin, School, Users, Wifi } from "lucide-react";
import type { ResearchSnapshot } from "@/lib/research";
import { Card } from "@/components/ui/card";
import { buttonClass } from "@/components/ui/button";
import type { Locale } from "@/types/domain";
const tooltipStyle={backgroundColor:"#102a2a",border:"1px solid #829492",borderRadius:"8px",color:"#fff"},axisTick={fontSize:11,fill:"#334155"};
export function ResearchDashboard({locale,data}:{locale:Locale;data:ResearchSnapshot}){
  const uz=locale==="uz",notice=data.mode==="demo"?(uz?"Namoyish ma’lumotlari — haqiqiy pilot natijalari emas.":"Illustrative demo data — not real pilot findings."):data.mode==="insufficient"?(uz?`Jonli ma’lumot yetarli emas. Kamida ${data.minimumGroupSize} ta yakunlangan urinish kerak.`:`Insufficient live data. At least ${data.minimumGroupSize} completed attempts are required.`):(uz?"Anonimlashtirilgan jonli pilot natijalari. Taqqoslashlar tavsifiy, statistik xulosa emas.":data.notice);
  const stats=[{Icon:Users,value:data.participants.toLocaleString(),label:uz?"Ishtirokchi":"Participants",note:data.mode},{Icon:MapPin,value:String(data.regionalScores.length),label:uz?"Ko‘rsatilgan hudud":"Reported regions",note:`n ≥ ${data.minimumGroupSize}`},{Icon:School,value:`${data.completionRate}%`,label:uz?"Yakunlash darajasi":"Completion rate",note:uz?`${data.completed} yakunlangan`:`${data.completed} complete`},{Icon:Wifi,value:`${Math.round(data.averageDurationSeconds/60)} ${uz?"daq":"min"}`,label:uz?"O‘rtacha vaqt":"Average duration",note:data.mode}];
  const chart=(values:unknown[],key:string,color:string)=><div className="mt-5 h-80 min-w-0"><ResponsiveContainer width="100%" height="100%"><BarChart data={values} margin={{left:-12,right:8}}><CartesianGrid stroke="#cbd5d4" strokeDasharray="3 3" vertical={false}/><XAxis dataKey={key} tick={axisTick} interval={0}/><YAxis domain={[0,100]} tick={axisTick}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="score" fill={color} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div>;
  return <div className="container-shell py-10 lg:py-16"><div className="mb-6 rounded-lg border border-blue-300 bg-blue-50 p-3 text-sm font-medium text-blue-950">{notice}</div><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-700">{uz?"Anonim pilot tahlili":"Anonymous pilot intelligence"}</p><h1 className="display mt-3 text-4xl font-semibold text-ink sm:text-5xl">{uz?"Raqamli ko‘nikmalar tadqiqot paneli":"Digital skills research dashboard"}</h1><p className="mt-3 max-w-2xl text-secondary-text">{uz?"Hudud, sinf va imkoniyat bo‘yicha umumlashtirilgan ko‘rsatkichlar. Shaxsiy ma’lumot ko‘rsatilmaydi.":"Aggregated patterns by region, grade, and access. No personally identifiable student data is shown."}</p></div><Link href="/api/research/export" className={buttonClass("secondary")}><Download size={17}/>{uz?"CSV yuklash":"Export CSV"}</Link></div>
    <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({Icon,value,label,note})=><Card key={label}><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-lg bg-teal-50 text-teal-700"><Icon size={20}/></span><span className="text-xs text-slate-500">{note}</span></div><strong className="mt-6 block font-serif text-4xl text-ink">{value}</strong><span className="text-sm text-secondary-text">{label}</span></Card>)}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="overflow-hidden"><h2 className="font-bold">{uz?"Hududlar bo‘yicha o‘rtacha ball":"Average score by region"}</h2><p className="text-sm text-secondary-text">{uz?"0–100 oralig‘idagi me’yorlangan ball":"0–100 normalized score"}</p>{chart(data.regionalScores,"region","#0f766e")}</Card><Card className="overflow-hidden"><h2 className="font-bold">{uz?"Sinf bo‘yicha o‘rtacha ball":"Average score by grade"}</h2>{chart(data.gradeScores,"grade","#6d4bc3")}</Card><Card className="overflow-hidden"><h2 className="font-bold">{uz?"Ko‘nikma yo‘nalishlari taqqoslanishi":"Category comparison"}</h2>{chart(data.categoryAverages,"name","#245f9e")}</Card><Card className="overflow-hidden"><h2 className="font-bold">{uz?"Ball taqsimoti":"Score distribution"}</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.scoreDistribution} margin={{left:-12,right:8}}><CartesianGrid stroke="#cbd5d4" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="range" tick={axisTick}/><YAxis tick={axisTick}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="students" fill="#6d4bc3" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card></div>
    <Card className="mt-5 bg-amber-50"><h2 className="font-bold text-amber-950">{uz?"Tadqiqot eslatmasi":"Research note"}</h2><p className="mt-2 text-sm leading-6 text-amber-950">{uz?"Pilot natijalari O‘zbekistonning barcha o‘quvchilarini ifodalamaydi. Ochiq hisobotda kichik guruhlar yashirilishi kerak. Farqlar faqat shu namunani tavsiflaydi va sababni isbotlamaydi.":"Pilot findings are not representative of all students in Uzbekistan. Small groups must be suppressed before public reporting. Differences describe this sample and do not establish causation."}</p></Card>
  </div>;
}
