"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft,ArrowRight,Check,Clock3 } from "lucide-react";
import type { Locale } from "@/types/domain";
import type { PublicV2Item } from "@/lib/assessment/v2-bank";
import { Button } from "@/components/ui/button";import{Badge}from"@/components/ui/badge";import{Progress}from"@/components/ui/progress";import{cn}from"@/utils/cn";

function stored<T>(key:string,fallback:T){if(typeof window==="undefined")return fallback;try{return JSON.parse(sessionStorage.getItem(key)||"")as T}catch{return fallback}}
function looksLikeCode(item:PublicV2Item){return item.questionType==="code_tracing"||/\b(IF|ELSE|ENDIF|FOR|NEXT)\b|←|:=|=>/.test(item.context)}
export function AssessmentRunner({locale}:{locale:Locale}){
  const uz=locale==="uz",router=useRouter(),[core,setCore]=useState<PublicV2Item[]>([]),[isolation,setIsolation]=useState<PublicV2Item[]>(()=>stored("skillmap-v2-isolation",[])),[stage,setStage]=useState<"core"|"isolation">(()=>stored("skillmap-v2-stage","core")),[index,setIndex]=useState(()=>stored("skillmap-v2-page",0)),[answers,setAnswers]=useState<Record<string,string>>(()=>stored("skillmap-v2-answers",{})),[version,setVersion]=useState(""),[submitting,setSubmitting]=useState(false),timings=useRef<Record<string,number>>(stored("skillmap-v2-timings",{})),started=useRef(Date.now()),answersRef=useRef(answers),isolationRef=useRef(isolation);
  answersRef.current=answers;isolationRef.current=isolation;
  useEffect(()=>{fetch(`/api/assessment/v2?locale=${locale}`).then(r=>r.json()).then(data=>{setCore(data.items);setVersion(data.assessmentVersion);if(isolationRef.current.length)fetch("/api/assessment/v2/branch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale,answers:answersRef.current})}).then(r=>r.json()).then(x=>{setIsolation(x.items);sessionStorage.setItem("skillmap-v2-isolation",JSON.stringify(x.items))})})},[locale]);
  const items=stage==="core"?core:isolation,item=items[index],answered=items.filter(i=>answers[i.itemId]).length;
  function choose(id:string,value:string){timings.current[id]=(timings.current[id]??0)+(Date.now()-started.current);started.current=Date.now();const next={...answers,[id]:value};setAnswers(next);sessionStorage.setItem("skillmap-v2-answers",JSON.stringify(next))}
  function move(next:number){setIndex(next);sessionStorage.setItem("skillmap-v2-page",JSON.stringify(next));started.current=Date.now();scrollTo(0,0)}
  async function nextStage(){if(core.some(i=>!answers[i.itemId])){alert(uz?"Davom etishdan oldin barcha 30 savolga javob bering.":"Answer all 30 questions before continuing.");return}setSubmitting(true);const response=await fetch("/api/assessment/v2/branch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale,answers})});const data=await response.json();setIsolation(data.items);sessionStorage.setItem("skillmap-v2-isolation",JSON.stringify(data.items));if(data.items.length){setStage("isolation");sessionStorage.setItem("skillmap-v2-stage",JSON.stringify("isolation"));move(0);setSubmitting(false)}else await finish(data.items)}
  async function finish(branch=isolation){setSubmitting(true);const participant=stored("skillmap-participant",null),submissionKey=sessionStorage.getItem("skillmap-submission-key")||crypto.randomUUID();sessionStorage.setItem("skillmap-submission-key",submissionKey);sessionStorage.setItem("skillmap-v2-timings",JSON.stringify(timings.current));try{const response=await fetch("/api/attempts/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({submissionKey,participant,assessmentVersion:version,itemIds:[...core,...branch].map(i=>i.itemId),answers,timings:timings.current})});if(!response.ok)throw new Error();const payload=await response.json();sessionStorage.setItem("skillmap-v2-result",JSON.stringify(payload));sessionStorage.setItem("skillmap-submitted","true");router.push(`/${locale}/results`)}catch{alert(uz?"Natijani yuborib bo‘lmadi. Jarayoningiz saqlanib qoldi.":"Submission failed. Your progress is preserved.");setSubmitting(false)}}
  if(!item)return <div className="container-shell py-16 text-center">{uz?"Baholash yuklanmoqda…":"Loading assessment…"}</div>;
  const final=index===items.length-1,selected=answers[item.itemId];
  return <div className="container-shell py-8 lg:py-14"><div className="mx-auto max-w-3xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Badge>{stage==="core"?(uz?"Asosiy baholash":"Common Core"):(uz?"Qo‘shimcha diagnostika":"Diagnostic follow-up")}</Badge><h1 className="display mt-4 text-3xl font-semibold">{stage==="core"?(uz?`${index+1}-savol, 30 tadan`:`Question ${index+1} of 30`):(uz?`${index+1}-qo‘shimcha savol, ${items.length} tadan`:`Follow-up ${index+1} of ${items.length}`)}</h1>{stage==="isolation"&&<p className="mt-2 text-secondary-text">{uz?"Hozirgi ko‘nikmalaringizni yaxshiroq tushunish uchun bir nechta qo‘shimcha savol beramiz.":"We’ll ask a few additional questions to better understand your current skills."}</p>}</div><div className="flex items-center gap-2 text-sm text-secondary-text"><Clock3 size={17}/>{uz?"20–30 daqiqa":"20–30 min"}</div></div>
    <div className="mt-7"><Progress value={Math.round((index+Number(Boolean(selected)))/items.length*100)} label={`${answered} / ${items.length}`}/></div>
    <article className="mt-7 rounded-2xl border border-ui-border bg-surface p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-teal-800">{uz?"Vaziyat":"Context"}</p>{looksLikeCode(item)?<pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-4 font-mono text-sm leading-6 text-white"><code>{item.context.replaceAll("; ",";\n")}</code></pre>:<p className="mt-3 whitespace-pre-wrap leading-7 text-secondary-text">{item.context}</p>}<div className="my-6 border-t border-slate-200"/><p className="text-xs font-bold uppercase tracking-wider text-teal-800">{uz?"Savol":"Question"}</p><h2 className="mt-3 text-xl font-bold leading-8 text-ink">{item.question}</h2><fieldset className="mt-7"><legend className="text-xs font-bold uppercase tracking-wider text-slate-600">{uz?"Javob variantlari":"Answer options"}</legend><div className="mt-3 grid gap-3">{item.options.map(option=>{const active=selected===option.id;return <label key={option.id} className={cn("flex min-h-14 cursor-pointer items-start gap-3 rounded-xl border p-4 text-sm leading-6 focus-within:ring-2 focus-within:ring-focus-ring",active?"border-teal-800 bg-teal-50 font-semibold":"border-strong-border bg-white hover:bg-slate-50")}><input className="sr-only" type="radio" name={item.itemId} checked={active} onChange={()=>choose(item.itemId,option.id)}/><span aria-hidden className={cn("mt-0.5 grid size-5 shrink-0 place-items-center rounded-full border-2",active?"border-teal-800 bg-teal-800 text-white":"border-slate-500")}>{active&&<Check size={12}/>}</span><span><strong className="mr-2">{option.id}.</strong>{option.label}</span></label>})}</div></fieldset></article>
    <div className="mt-6 flex justify-between gap-3"><Button disabled={index===0} onClick={()=>move(index-1)}><ArrowLeft size={17}/>{uz?"Orqaga":"Back"}</Button>{!final?<Button disabled={!selected} onClick={()=>move(index+1)}>{uz?"Keyingi":"Next"}<ArrowRight size={17}/></Button>:stage==="core"?<Button disabled={submitting||!selected} onClick={nextStage}>{uz?"Davom etish":"Continue"}<ArrowRight size={17}/></Button>:<Button disabled={submitting||!selected} onClick={()=>finish()}>{uz?"Natijani ko‘rish":"View results"}<ArrowRight size={17}/></Button>}</div>
  </div></div>
}
