"use client";
import {useState,type ReactNode} from "react";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {z} from "zod";
import {ShieldCheck} from "lucide-react";
import {profileSchema} from "@/validation/schemas";
import {generateLocalParticipantCode} from "@/lib/participant";
import {Button} from "@/components/ui/button";
import {Input,Select} from "@/components/ui/forms";
import type {Locale,ParticipantProfile} from "@/types/domain";
type Values=z.infer<typeof profileSchema>;
export function ParticipantOnboarding({locale,onComplete}:{locale:Locale;onComplete:(profile:ParticipantProfile)=>void}){const uz=locale==="uz",[notice,setNotice]=useState(true),{register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(profileSchema),defaultValues:{preferredLocale:locale,consent:true,externalApprovalHandled:true,consentedAt:new Date().toISOString(),careerGoal:"general-digital-skills",region:"Not collected",district:"Not collected",schoolType:"other",englishLevel:"beginner",deviceAccess:"personal",internetAccess:"reliable",programmingExperience:"none"}});if(notice)return <div className="container-shell grid min-h-[600px] place-items-center py-10"><section className="w-full max-w-xl rounded-2xl border border-ui-border bg-surface p-6 sm:p-9"><ShieldCheck className="text-teal-800" size={34}/><h1 className="display mt-5 text-4xl font-semibold">{uz?"Baholashni boshlash":"Start your assessment"}</h1><p className="mt-4 leading-7 text-secondary-text">{uz?"Natijangizni saqlash va sizga ko‘rsatish uchun faqat ism, familiya va sinf so‘raladi.":"Only your first name, last name, and grade are requested to identify and save your result."}</p><p className="mt-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-700">{uz?"Telefon, pasport, manzil yoki maktab ma’lumotlari so‘ralmaydi.":"Phone, passport, address, and school details are not requested."}</p><Button className="mt-7 w-full" onClick={()=>setNotice(false)}>{uz?"Davom etish":"Continue"}</Button></section></div>;const submit=(values:Values)=>onComplete({...values,participantCode:generateLocalParticipantCode(),grade:values.grade as 8|9|10|11});return <div className="container-shell py-10"><form onSubmit={handleSubmit(submit)} className="mx-auto max-w-xl rounded-2xl border border-ui-border bg-surface p-5 sm:p-8"><h1 className="display text-3xl font-semibold">{uz?"O‘zingiz haqingizda":"About you"}</h1><p className="mt-2 text-sm text-secondary-text">{uz?"Uchta maydonni to‘ldiring va testni boshlang.":"Complete these three fields to begin."}</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label={uz?"Ism":"First name"} error={errors.firstName?.message}><Input autoComplete="given-name" {...register("firstName")}/></Field><Field label={uz?"Familiya":"Last name"} error={errors.lastName?.message}><Input autoComplete="family-name" {...register("lastName")}/></Field><Field label={uz?"Sinf":"Grade"} error={errors.grade?(uz?"8–11-sinflardan birini tanlang.":errors.grade.message):undefined}><Select {...register("grade",{valueAsNumber:true})}><option value="">—</option>{[8,9,10,11].map(grade=><option key={grade} value={grade}>{grade}</option>)}</Select></Field></div><Button className="mt-7 w-full">{uz?"Testni boshlash":"Start assessment"}</Button></form></div>}
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="block text-sm font-bold">{label}<span className="mt-2 block">{children}</span>{error&&<span className="mt-1 block text-xs text-red-700">{error}</span>}</label>}
