"use client";
import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ShieldCheck } from "lucide-react";
import { profileSchema } from "@/validation/schemas";
import { generateLocalParticipantCode } from "@/lib/participant";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/forms";
import type { Locale, ParticipantProfile } from "@/types/domain";
type Values=z.infer<typeof profileSchema>;
const labels={schoolType:{public:["Public","Davlat"],private:["Private","Xususiy"],specialized:["Specialized","Ixtisoslashtirilgan"],other:["Other","Boshqa"]},englishLevel:{beginner:["Beginner","Boshlang‘ich"],elementary:["Elementary","Elementar"],intermediate:["Intermediate","O‘rta"],advanced:["Advanced","Yuqori"]},deviceAccess:{personal:["Personal","Shaxsiy"],shared:["Shared","Umumiy"],"school-only":["School only","Faqat maktabda"],none:["None","Yo‘q"]},internetAccess:{reliable:["Reliable","Barqaror"],limited:["Limited","Cheklangan"],rare:["Rare","Kamdan-kam"],none:["None","Yo‘q"]},programmingExperience:{none:["None","Yo‘q"],"less-than-year":["Less than one year","Bir yildan kam"],"one-to-two":["1–2 years","1–2 yil"],"more-than-two":["More than two years","Ikki yildan ko‘p"]}} as const;
function Options({group,uz}:{group:keyof typeof labels;uz:boolean}){return Object.entries(labels[group]).map(([value,text])=><option key={value} value={value}>{text[uz?1:0]}</option>)}
export function ParticipantOnboarding({locale,onComplete}:{locale:Locale;onComplete:(profile:ParticipantProfile)=>void}){
  const uz=locale==="uz",[notice,setNotice]=useState(true),{register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(profileSchema),defaultValues:{preferredLocale:locale,consent:true,externalApprovalHandled:false,consentedAt:new Date().toISOString()}});
  if(notice)return <div className="container-shell grid min-h-[650px] place-items-center py-10"><section className="w-full max-w-2xl rounded-2xl border border-ui-border bg-surface p-6 sm:p-9"><ShieldCheck className="text-teal-800" size={34}/><p className="mt-5 text-xs font-bold uppercase tracking-widest text-teal-800">{uz?"Ishtirok va ma’lumotlardan foydalanish":"Participation and data use"}</p><h1 className="display mt-3 text-4xl font-semibold">{uz?"Ta’limiy pilotda ishtirok etish":"Take part in an educational pilot"}</h1><ul className="mt-6 list-disc space-y-3 pl-5 text-secondary-text"><li>{uz?"Ishtirok ixtiyoriy; bu rasmiy davlat imtihoni emas.":"Participation is voluntary; this is not an official government examination."}</li><li>{uz?"Javoblar anonim tahlil qilinadi; umumlashtirilgan natijalar pilot hisobotiga kirishi mumkin.":"Answers are analyzed anonymously; aggregated findings may appear in a pilot report."}</li><li>{uz?"Yuborishdan oldin istalgan payt to‘xtashingiz mumkin.":"You may stop at any time before submission."}</li><li>{uz?"Ism, telefon, pasport yoki aniq manzil so‘ralmaydi.":"No name, phone, passport, or exact address is required."}</li></ul><p className="mt-5 rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">{uz?"Voyaga yetmaganlar uchun zarur ruxsat pilot tashkilotchisi tomonidan tashqarida boshqariladi. Bu huquqiy muvofiqlik da’vosi emas.":"Any approval required for minors is handled externally by the pilot organizer. This is not a legal-compliance claim."}</p><Button className="mt-7 w-full sm:w-auto" onClick={()=>setNotice(false)}>{uz?"Tushundim — davom etish":"I understand — continue"}</Button></section></div>;
  const submit=(values:Values)=>onComplete({...values,participantCode:generateLocalParticipantCode(),grade:values.grade as 8|9|10|11});
  return <div className="container-shell py-10"><form onSubmit={handleSubmit(submit)} className="mx-auto max-w-3xl rounded-2xl border border-ui-border bg-surface p-5 sm:p-8"><h1 className="display text-3xl font-semibold">{uz?"Pilot ishtirokchisi haqida":"Pilot participant context"}</h1><p className="mt-2 text-sm text-secondary-text">{uz?"Faqat natijani talqin qilish uchun zarur ma’lumotlar.":"Only information needed to interpret results."}</p><div className="mt-7 grid gap-5 sm:grid-cols-2">
    <Field label={uz?"Sinf":"Grade"} error={errors.grade?(uz?"8–11-sinflardan birini tanlang.":errors.grade.message):undefined}><Select {...register("grade",{valueAsNumber:true})}><option value="">—</option>{[8,9,10,11].map((grade)=><option key={grade}>{grade}</option>)}</Select></Field>
    <Field label={uz?"Hudud":"Region"}><Input {...register("region")}/></Field><Field label={uz?"Tuman/shahar":"District or city"}><Input {...register("district")}/></Field>
    <Field label={uz?"Maktab turi":"School type"}><Select {...register("schoolType")}><Options group="schoolType" uz={uz}/></Select></Field><Field label={uz?"Pilot kohort kodi":"Pilot cohort code"}><Input {...register("cohortCode")}/></Field>
    <Field label={uz?"Ingliz tili":"English level"}><Select {...register("englishLevel")}><Options group="englishLevel" uz={uz}/></Select></Field><Field label={uz?"Qurilma":"Device access"}><Select {...register("deviceAccess")}><Options group="deviceAccess" uz={uz}/></Select></Field>
    <Field label={uz?"Internet":"Internet access"}><Select {...register("internetAccess")}><Options group="internetAccess" uz={uz}/></Select></Field><Field label={uz?"Dasturlash tajribasi":"Programming experience"}><Select {...register("programmingExperience")}><Options group="programmingExperience" uz={uz}/></Select></Field>
  </div><label className="mt-7 flex gap-3 rounded-xl border border-ui-border bg-slate-50 p-4 text-sm"><input type="checkbox" className="mt-1 size-4" {...register("externalApprovalHandled")}/><span>{uz?"Tashkilotchi zarur tashqi ruxsatni boshqarganini tasdiqlayman.":"I confirm the organizer handled any required external approval."}</span></label><input type="hidden" {...register("preferredLocale")}/><input type="hidden" {...register("consentedAt")}/><input type="hidden" value="true" {...register("consent")}/><Button className="mt-7 w-full sm:w-auto">{uz?"Rozilik berish va boshlash":"Consent and start"}</Button></form></div>;
}
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="block text-sm font-bold">{label}<span className="mt-2 block">{children}</span>{error&&<span className="mt-1 block text-xs text-red-700">{error}</span>}</label>}
