/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase generated types are not available in this project. */
import "server-only";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { calculateItemAnalytics } from "@/lib/analytics";

function client(){const value=createSupabaseAdminClient();if(!value)throw new Error("Supabase admin mode is not configured");return value}
export async function getAdminOverview(){const admin=client();const [{count:participants},{data:attempts},{data:questions},{data:settings}]=await Promise.all([admin.from("pilot_participants").select("id",{count:"exact",head:true}),admin.from("assessment_attempts").select("id,status,overall_score,locale,started_at,completed_at,duration_seconds,pilot_participants(participant_code,grade,region,cohort_code)").not("anonymous_id","is",null).order("started_at",{ascending:false}),admin.from("questions").select("status,review_status,publishable"),admin.from("pilot_settings").select("pilot_name,pilot_start_date,pilot_end_date,minimum_group_size,feedback_mode").eq("id",true).maybeSingle()]);const all=attempts??[],completed=all.filter(item=>item.status==="completed"),minimum=settings?.minimum_group_size??5;return{participants:participants??0,attempts:all.length,completed:completed.length,completionRate:all.length?Math.round(completed.length/all.length*100):0,published:(questions??[]).filter(item=>item.status==="published").length,needsReview:(questions??[]).filter(item=>item.review_status==="needs_review").length,doNotPublish:(questions??[]).filter(item=>item.review_status==="do_not_publish").length,settings:settings??{pilot_name:"SkillMap internal pilot",pilot_start_date:null,pilot_end_date:null,minimum_group_size:5,feedback_mode:"research-safe"},researchSufficient:completed.length>=minimum,recent:all.slice(0,8) as any[]};}

export async function getAdminQuestions(){const admin=client(),[{data:items},{data:options}]=await Promise.all([admin.from("questions").select("stable_id,version,status,review_status,review_notes,category,competency_code,competency_name,question_type,difficulty,estimated_time_seconds,prompt_en,prompt_uz,learning_objective,roadmap_skill_mapping,misconception_id,misconception_description,tags,correct_answer,explanation_en,explanation_uz,distractor_analysis,publishable").not("stable_id","is",null).order("category").order("stable_id"),admin.from("question_options").select("question_id,label_en,label_uz,is_correct,position,questions!inner(id,stable_id,version)").order("position")]);const optionMap=new Map<string,any[]>();for(const option of options??[]){const q=(option as any).questions,key=`${q.stable_id}@${q.version}`,list=optionMap.get(key)??[];list.push({labelEn:option.label_en,labelUz:option.label_uz,isCorrect:option.is_correct,position:option.position});optionMap.set(key,list)}return(items??[]).map(item=>({id:item.stable_id,version:item.version,status:item.status,reviewStatus:item.review_status,reviewNotes:item.review_notes??[],category:item.category,competencyCode:item.competency_code,competencyName:item.competency_name,type:item.question_type,difficulty:item.difficulty,estimatedTimeSeconds:item.estimated_time_seconds,promptEn:item.prompt_en,promptUz:item.prompt_uz,learningObjective:item.learning_objective,roadmapMapping:item.roadmap_skill_mapping,misconceptionId:item.misconception_id,misconceptionDescription:item.misconception_description,tags:item.tags??[],correctAnswer:item.correct_answer,explanationEn:item.explanation_en,explanationUz:item.explanation_uz,distractorAnalysis:item.distractor_analysis,publishable:item.publishable,options:optionMap.get(`${item.stable_id}@${item.version}`)??[]}));}

export async function getAdminParticipants(){const admin=client(),{data}=await admin.from("assessment_attempts").select("id,status,locale,overall_score,skill_level,started_at,completed_at,duration_seconds,pilot_participants!inner(participant_code,grade,region,district,cohort_code,preferred_locale)").not("anonymous_id","is",null).order("started_at",{ascending:false});return(data??[]).map((row:any)=>({id:row.id,status:row.status,locale:row.locale,overallScore:row.overall_score,skillLevel:row.skill_level,startedAt:row.started_at,completedAt:row.completed_at,durationSeconds:row.duration_seconds,participantCode:row.pilot_participants.participant_code,grade:row.pilot_participants.grade,region:row.pilot_participants.region,district:row.pilot_participants.district,cohort:row.pilot_participants.cohort_code,preferredLocale:row.pilot_participants.preferred_locale}));}

export async function getAdminItemAnalytics(){const admin=client(),[{data:responses},{data:questions},{data:settings}]=await Promise.all([admin.from("pilot_responses").select("question_stable_id,question_version,selected_answer,response_time_ms,item_score,rapid_response,assessment_attempts!inner(locale,overall_score)"),admin.from("questions").select("stable_id,version,prompt_en,prompt_uz,category,competency_code,status,review_status").not("stable_id","is",null).order("stable_id"),admin.from("pilot_settings").select("minimum_group_size").eq("id",true).maybeSingle()]);const grouped=new Map<string,any[]>();for(const row of responses??[]){const key=`${row.question_stable_id}@${row.question_version}`,answer=row.selected_answer,selected=answer==null?[]:typeof answer==="string"?[answer]:Array.isArray(answer)?answer:"order" in answer?answer.order:Object.values(answer.matches??{});const attempt=(row as any).assessment_attempts,list=grouped.get(key)??[];list.push({correct:Number(row.item_score)===1,responseTimeMs:row.response_time_ms,selected,omitted:row.selected_answer==null,rapid:row.rapid_response,language:attempt.locale,totalScore:Number(attempt.overall_score??0)});grouped.set(key,list)}const minimum=Math.max(20,settings?.minimum_group_size??5);return(questions??[]).map(question=>({id:question.stable_id,version:question.version,promptEn:question.prompt_en,promptUz:question.prompt_uz,category:question.category,competencyCode:question.competency_code,status:question.status,reviewStatus:question.review_status,analytics:calculateItemAnalytics(grouped.get(`${question.stable_id}@${question.version}`)??[],minimum),minimum}));}

export async function getPilotSettings(){const admin=client(),{data,error}=await admin.from("pilot_settings").select("pilot_name,pilot_start_date,pilot_end_date,minimum_group_size,feedback_mode,updated_at").eq("id",true).single();if(error||!data)throw new Error("Pilot settings are unavailable");return data}
export async function getActivityLog(){const admin=client(),{data}=await admin.from("activity_logs").select("id,created_at,actor_id,action,entity_type,entity_id,metadata").order("created_at",{ascending:false}).limit(100);return data??[]}
