import type {RoadmapNode} from "@/lib/cs-roadmap";
import type {V2Domain} from "@/lib/assessment/v2-bank";
import type {Locale} from "@/types/domain";
import {resourcesForDomain,type LearningResource} from "@/lib/learning-resources";

export type NodeDetail={keyConceptsEn:string[];keyConceptsUz:string[];learn:LearningResource[];practice:LearningResource[];taskEn:string;taskUz:string;checkpointEn:string;checkpointUz:string;internalPractice:boolean};
const domainByStage:Record<number,V2Domain>={1:"Digital & Information Literacy",2:"Computational Thinking & Algorithms",3:"Programming Fundamentals",4:"Computational Thinking & Algorithms",5:"Systems, Networks & Cybersecurity",6:"Systems, Networks & Cybersecurity",7:"Data & Databases",8:"Programming Fundamentals",9:"AI Literacy",10:"Programming Fundamentals"};
const concepts:Record<number,{en:string[];uz:string[]}>=
{1:{en:["files","folders","search query","source check","privacy","account safety"],uz:["fayl","papka","qidiruv so‘rovi","manbani tekshirish","maxfiylik","hisob xavfsizligi"]},2:{en:["input","steps","condition","pattern","algorithm","test case"],uz:["kirish ma’lumoti","qadamlar","shart","andoza","algoritm","test holati"]},3:{en:["variable","input","if/else","for loop","while loop","function","debugging"],uz:["o‘zgaruvchi","kiritish","if/else","for sikli","while sikli","funksiya","xatoni tuzatish"]},4:{en:["array","string","index","search","sort","stack","queue","complexity"],uz:["massiv","satr","indeks","qidirish","saralash","stek","navbat","murakkablik"]},5:{en:["CPU","RAM","storage","process","operating system","input/output"],uz:["protsessor","RAM","saqlash","jarayon","operatsion tizim","kiritish/chiqarish"]},6:{en:["IP address","DNS","packet","router","HTTP","HTTPS","authentication","encryption"],uz:["IP manzil","DNS","paket","router","HTTP","HTTPS","autentifikatsiya","shifrlash"]},7:{en:["table","row","column","primary key","SELECT","WHERE","ORDER BY","NULL"],uz:["jadval","qator","ustun","asosiy kalit","SELECT","WHERE","ORDER BY","NULL"]},8:{en:["Git","commit","module","API","frontend","backend","test","release"],uz:["Git","commit","modul","API","frontend","backend","test","reliz"]},9:{en:["training data","model","prediction","bias","prompt","verification","human review","privacy"],uz:["o‘rgatish ma’lumoti","model","bashorat","tarafkashlik","prompt","tekshiruv","inson nazorati","maxfiylik"]},10:{en:["specialization","portfolio","project scope","requirements","testing","deployment","documentation","teamwork"],uz:["yo‘nalish","portfolio","loyiha hajmi","talablar","testlash","joylashtirish","hujjatlash","jamoaviy ish"]}};
const practical=new Set(["interactive","practice","problem","project"]);
export function nodeDetail(node:RoadmapNode,locale:Locale="uz"):NodeDetail{const domain=domainByStage[node.stage],all=resourcesForDomain(domain,locale),learn=all.filter(r=>r.resourceType==="course"||r.resourceType==="video"||r.resourceType==="article").slice(0,3),practice=all.filter(r=>practical.has(r.resourceType)).slice(0,3),base=concepts[node.stage];const titleEn=node.titleEn.split(/,| and | & /).map(v=>v.trim().toLowerCase()).filter(Boolean),titleUz=node.titleUz.split(/,| va | & /).map(v=>v.trim().toLowerCase()).filter(Boolean),count=node.difficulty==="foundation"?6:node.difficulty==="intermediate"?8:10,keyConceptsEn=[...new Set([...titleEn,...base.en])].slice(0,count),keyConceptsUz=[...new Set([...titleUz,...base.uz])].slice(0,count);return{keyConceptsEn,keyConceptsUz,learn:learn.length?learn:all.slice(0,3),practice,internalPractice:practice.length===0,taskEn:`Create one small example that uses ${keyConceptsEn.slice(0,3).join(", ")}. Test it with three different inputs and explain the result.`,taskUz:`${keyConceptsUz.slice(0,3).join(", ")} ishlatilgan bitta kichik misol yarating. Uni uch xil kiritish bilan tekshirib, natijani tushuntiring.`,checkpointEn:`The example works for all three tests, and you can explain ${keyConceptsEn.slice(0,2).join(" and ")} without notes.`,checkpointUz:`Misol uchala testda ishlaydi va ${keyConceptsUz.slice(0,2).join(" hamda ")}ni qaydlarsiz tushuntira olasiz.`}}
