import { assessmentCategories, categoryDefinitions, competencyDefinitions, difficultyWeights, scoringConfiguration, type CompetencyCode } from "@/constants/methodology";
import type { AssessmentItem, AssessmentResult, DetectedMisconception, ItemResponse, StructuredAnswer } from "@/types/domain";

function selected(answer:StructuredAnswer|null):string[]{if(answer==null)return[];if(typeof answer==="string")return[answer];if(Array.isArray(answer))return answer;if("order" in answer)return answer.order;return Object.entries(answer.matches).map(([left,right])=>`${left}:${right}`)}
export function scoreSelectMultiple(correct:string[],answer:string[]){const expected=new Set(correct),chosen=new Set(answer),matches=[...chosen].filter((value)=>expected.has(value)).length,incorrect=[...chosen].filter((value)=>!expected.has(value)).length;return Math.max(0,(matches-incorrect)/expected.size)}
export function scoreRanking(correct:string[],answer:string[]){if(correct.length<2||answer.length!==correct.length||new Set(answer).size!==answer.length)return 0;const positions=new Map(answer.map((value,index)=>[value,index]));let discordant=0,total=0;for(let first=0;first<correct.length;first++)for(let second=first+1;second<correct.length;second++){total++;if((positions.get(correct[first])??Infinity)>(positions.get(correct[second])??Infinity))discordant++}return total?1-discordant/total:1}
export function scoreMatching(correct:Record<string,string>,answer:Record<string,string>){const keys=Object.keys(correct);return keys.length?keys.filter((key)=>answer[key]===correct[key]).length/keys.length:0}
export function scoreItem(item:AssessmentItem,answer:StructuredAnswer|null){if(answer==null)return 0;const correct=item.correctAnswer;if(item.type==="select-multiple"&&Array.isArray(correct))return scoreSelectMultiple(correct,selected(answer));if(item.type==="ranking"&&typeof correct==="object"&&!Array.isArray(correct)&&"order" in correct&&typeof answer==="object"&&!Array.isArray(answer)&&"order" in answer)return scoreRanking(correct.order,answer.order);if(item.type==="matching"&&typeof correct==="object"&&!Array.isArray(correct)&&"matches" in correct&&typeof answer==="object"&&!Array.isArray(answer)&&"matches" in answer)return scoreMatching(correct.matches,answer.matches);return typeof correct==="string"&&typeof answer==="string"&&correct===answer?1:0}
export function calculateResultCoverage(answeredCount:number,totalCount:number,competencies:{answered:number}[]){const itemRatio=answeredCount/Math.max(totalCount,1),adequateRatio=competencies.filter((item)=>item.answered>=2).length/Math.max(competencies.length,1);return Math.round((itemRatio+adequateRatio)/2*100)}
export function scoreAssessment(items:AssessmentItem[],answers:Record<string,string|StructuredAnswer>,timings:Record<string,number>={}):AssessmentResult{return scoreResponses(items,items.map((item)=>({questionId:item.id,answer:answers[item.id]??null,responseTimeMs:timings[item.id]??0})))}
export function scoreResponses(items:AssessmentItem[],responses:ItemResponse[]):AssessmentResult{
  const responseMap=new Map(responses.map((response)=>[response.questionId,response]));
  const rows=items.map((item)=>{const response=responseMap.get(item.id),fraction=scoreItem(item,response?.answer??null),possible=difficultyWeights[item.difficulty];return{item,fraction,earned:fraction*possible,possible,answered:response?.answer!=null,rapid:Boolean(response&&response.responseTimeMs>0&&response.responseTimeMs<item.estimatedTimeSeconds*1000*scoringConfiguration.rapidResponseThreshold)}});
  const categories=assessmentCategories.map((category)=>{const part=rows.filter((row)=>row.item.category===category),possible=part.reduce((sum,row)=>sum+row.possible,0),earned=part.reduce((sum,row)=>sum+row.earned,0);return{category,score:possible?Math.round(earned/possible*100):0,earned,possible,correct:part.filter((row)=>row.fraction===1).length,total:part.length}});
  const codes=[...new Set(items.map((item)=>item.competencyCode))] as CompetencyCode[];
  const competencies=codes.map((competencyCode)=>{const part=rows.filter((row)=>row.item.competencyCode===competencyCode),possible=part.reduce((sum,row)=>sum+row.possible,0),earned=part.reduce((sum,row)=>sum+row.earned,0),definition=competencyDefinitions[competencyCode];return{competencyCode,competencyName:definition.name,category:definition.category,score:possible?Math.round(earned/possible*100):0,earned,possible,answered:part.filter((row)=>row.answered).length,total:part.length}});
  const overall=Math.round(categories.reduce((sum,item)=>sum+item.score*categoryDefinitions[item.category].weight,0)),ordered=[...categories].sort((a,b)=>a.score-b.score),measuredCompetencies=competencies.filter((item)=>item.answered>0),competencyOrder=[...measuredCompetencies].sort((a,b)=>a.score-b.score);
  const misconceptionMap=new Map<string,DetectedMisconception>();for(const row of rows.filter((item)=>item.answered&&item.fraction<1)){const existing=misconceptionMap.get(row.item.misconceptionId),count=(existing?.count??0)+1;misconceptionMap.set(row.item.misconceptionId,{id:row.item.misconceptionId,description:row.item.misconceptionDescription,count,priority:count>=scoringConfiguration.misconceptionTriggerCount?"high":"monitor"})}
  const answeredCount=rows.filter((row)=>row.answered).length,coverage=calculateResultCoverage(answeredCount,rows.length,competencies);
  return{overall,level:overall<40?"Foundation":overall<65?"Developing":overall<85?"Proficient":"Advanced",coverage,coverageLabel:coverage<50?"Limited":coverage<80?"Partial":"Good",weakest:ordered[0]?.category??"digital-literacy",strongest:ordered.at(-1)?.category??"digital-literacy",weakestCompetency:competencyOrder[0]?.competencyCode??"DL-01",strongestCompetency:competencyOrder.at(-1)?.competencyCode??"DL-01",categories,competencies,misconceptions:[...misconceptionMap.values()].sort((a,b)=>b.count-a.count),answeredCount,totalCount:rows.length,rapidResponseFlags:rows.filter((row)=>row.rapid).map((row)=>row.item.id)};
}
