import type { Locale } from "@/types/domain";

const uz: Record<string, string> = {
  "Evaluating information": "Internet ma’lumotini tekshirish", "Managing digital identity": "Raqamli izni boshqarish", "Browsing, searching, and filtering": "Samarali internet qidiruvi", "Managing information": "Fayllarni tartibli saqlash", "Copyright and licenses": "Internet materialidan qonuniy foydalanish",
  "Algorithm design": "Algoritm qadamlarini tuzish", "Algorithmic reasoning": "Algoritmni qadam-baqadam bajarish", "Pattern recognition and generalization": "Qoidani misollardan topish", Decomposition: "Katta vazifani kichik qismlarga ajratish", Abstraction: "Muhim ma’lumotni ajratib olish",
  "Variables and state": "Python o‘zgaruvchilari", "Control flow": "Shartlar va sikllar", "Testing and validation": "Dasturni chegaraviy qiymatlarda tekshirish", "Hardware architecture": "Xotira va fayl saqlash", "Internet fundamentals": "Internetda ma’lumot yuborilishi", "Protecting personal data": "Phishing’dan himoyalanish", "Hardware and software": "Operatsion tizim vazifasi", Authentication: "Hisobni ikki bosqichli himoyalash",
  "Database structure": "Ma’lumotlar bazasida noyob ID", "Data quality": "Noto‘g‘ri ma’lumotni aniqlash", "Data types": "To‘g‘ri ma’lumot turini tanlash", "Spreadsheet reasoning": "Elektron jadval formulalari", "Validation and verification": "Kiritilgan ma’lumotni tekshirish", "Human agency": "AI qarorida inson nazorati", Verification: "AI javobini faktlar bilan tekshirish", Prompting: "AI’ga aniq topshiriq yozish", "Training data": "AI o‘rgangan ma’lumotning ta’siri", "Problem scoping": "AI uchun mos vazifani tanlash",
  "Assessing credibility": "Sayt va da’vo ishonchliligini tekshirish", "Persistence of data": "Internetga yuborilgan ma’lumot izi", "Search strategy refinement": "Qidiruv so‘zlarini aniqlashtirish", "File naming conventions in collaborative environments": "Guruh fayllarini tushunarli nomlash", "Creative Commons BY-NC": "Creative Commons litsenziyasi", "IPO stages": "Input, processing va output bosqichlari", "Rule-based sequencing": "Buyruqlarni to‘g‘ri tartibda bajarish", "Inferring transformation rules": "Misollardan o‘zgarish qoidasini topish", "Breaking a problem into sub-problems": "Muammoni kichik vazifalarga ajratish", "Removing irrelevant details": "Keraksiz tafsilotni olib tashlash",
  "Variable assignment": "O‘zgaruvchiga qiymat berish", "Iteration and accumulator tracking": "Sikl ichida natijani hisoblash", "Conditional selection": "if/else sharti", "Boolean conditional reasoning": "AND va OR shartlari", "Boundary test data": "Eng kichik va eng katta qiymatlarni test qilish", "Primary vs secondary storage": "RAM va doimiy xotira farqi", "Packet switching": "Internet paketlari", "Phishing and social engineering": "Soxta xat va havolani aniqlash", "OS vs applications": "Operatsion tizim va dastur farqi", "Multi-factor authentication": "Parol va tasdiqlash kodi",
  "Primary keys": "Jadvaldagi noyob asosiy kalit", "Handling outliers": "G‘ayrioddiy qiymatni tekshirish", "Contextual data type selection": "Butun va kasr son turini tanlash", "Relative cell referencing": "Formulani boshqa katakka nusxalash", "Validation vs verification": "Format tekshiruvi va qayta kiritish farqi", "Human accountability": "AI qarori uchun inson javobgarligi", "Plausible accuracy / hallucinations": "AI’ning ishonchli ko‘ringan xato javobi", "Iterative refinement with constraints": "AI topshirig‘ini uzunlik va auditoriya bilan aniqlashtirish", "Dataset bias and generalization": "AI o‘rgangan misollar yetarli bo‘lmaganda yuzaga keladigan xato", "Appropriate vs inappropriate AI use": "AI’dan xavfsiz va mos vazifada foydalanish",
};

const en: Record<string, string> = { "Iterative refinement with constraints": "Writing a clear AI request with audience and length", "Dataset bias and generalization": "How limited training examples cause AI mistakes", "Plausible accuracy / hallucinations": "Checking a confident but incorrect AI answer", "Rule-based sequencing": "Following rules in the correct order" };

export function studentTopicLabel(value: string, locale: Locale) { return locale === "uz" ? uz[value] ?? value : en[value] ?? value; }
