import "server-only";
import OpenAI from "openai";import{zodTextFormat}from"openai/helpers/zod";import{z}from"zod";
import type{V2Diagnostic,V2EvidenceSummary}from"@/lib/assessment/v2-results";
const week=z.object({week:z.union([z.literal(1),z.literal(2),z.literal(3),z.literal(4)]),focus:z.string().min(1),why:z.string().min(1),actions:z.array(z.string().min(1)).min(2).max(4),resourceIds:z.array(z.string()),practiceItemIds:z.array(z.string()),successCheck:z.string().min(1)});
export const roadmapSchema=z.object({summary:z.string().min(1),strengths:z.array(z.object({competency:z.string(),evidence:z.string()})),priorities:z.array(z.object({competency:z.string(),reason:z.string(),severity:z.enum(["high","medium","low"])})),roadmap:z.array(week).length(4),questionsToWorkOn:z.array(z.object({competency:z.string(),prompt:z.string()})),insufficientEvidence:z.array(z.string()),confidenceNote:z.string().min(1)});export type V2Roadmap=z.infer<typeof roadmapSchema>;
const unique=<T,>(values:T[])=>[...new Set(values)];
function priorityEvidence(e:V2EvidenceSummary){return[...e.diagnostics.filter(d=>d.classification!=="demonstrated")].sort((a,b)=>Number(b.classification==="possible_weakness")-Number(a.classification==="possible_weakness")||a.coreItemId.localeCompare(b.coreItemId))}
function focusLabel(d:V2Diagnostic,uz:boolean){return`${d.competency}: ${d.subCompetency}${d.classification==="possible_weakness"?(uz?" — asoslarni qayta ko‘rish":" — revisit foundations"):(uz?" — mustahkamlash":" — consolidate")}`}
function targetedWeek(d:V2Diagnostic,weekNumber:1|2,uz:boolean){const review=d.isolationItemId?[d.coreItemId,d.isolationItemId]:[d.coreItemId];return{week:weekNumber,focus:focusLabel(d,uz),why:d.classification==="possible_weakness"?(uz?`Asosiy va aniqlashtiruvchi javoblar ${d.subCompetency} mavzusini bosqichma-bosqich qayta ko‘rish foydali bo‘lishini ko‘rsatdi.`:`The Core and follow-up responses suggest a step-by-step review of ${d.subCompetency} would be useful.`):(uz?`Aniqlashtiruvchi javob ${d.subCompetency} bo‘yicha qisman tushuncha borligini ko‘rsatdi; endi uni mustahkamlash kerak.`:`The follow-up response showed partial understanding of ${d.subCompetency}; the next step is consolidation.`),actions:uz?[`${d.subCompetency} tushunchasini o‘z so‘zingiz bilan yozing va bitta to‘g‘ri misol keltiring.`,`SkillMap’dagi ${d.coreItemId} mavzusiga o‘xshash ikkita yangi vaziyat tuzing va har bir qarorni izohlang.`,`Xato yechimni to‘g‘ri yechim bilan taqqoslab, farqini 3 bandda yozing.`]:[`Explain ${d.subCompetency} in your own words and give one correct example.`,`Create two new situations similar to the topic in ${d.coreItemId} and justify each decision.`,`Compare an incorrect solution with a correct one and record three differences.`],resourceIds:[],practiceItemIds:review,successCheck:uz?`${d.subCompetency} bo‘yicha yangi misolni yordamsiz yechib, nega javob to‘g‘ri ekanini tushuntira olish.`:`Solve a new ${d.subCompetency} example without help and explain why the answer is correct.`}}
export function deterministicRoadmap(e:V2EvidenceSummary):V2Roadmap{
  const uz=e.locale==="uz",gaps=priorityEvidence(e),strengthDiagnostics=e.diagnostics.filter(d=>d.classification==="demonstrated"),strengths=unique(strengthDiagnostics.map(d=>d.competency)).slice(0,6),priorityItems=gaps.slice(0,4),fallbackStrength=strengthDiagnostics[0];
  const weeks:V2Roadmap["roadmap"]=[];
  if(priorityItems[0])weeks.push(targetedWeek(priorityItems[0],1,uz));else weeks.push({week:1,focus:uz?"Kuchli ko‘nikmani murakkabroq vaziyatga ko‘chirish":"Apply a demonstrated skill to a harder situation",why:uz?"Asosiy savollarda ustuvor bo‘shliq kuzatilmadi, shuning uchun reja rivojlanishga qaratiladi.":"No priority Core gap was observed, so the plan focuses on progression.",actions:uz?[`${fallbackStrength?.subCompetency??"Tanlangan ko‘nikma"} bo‘yicha murakkabroq vaziyat yarating.`,`Ikki mumkin bo‘lgan yechimni mezonlar asosida taqqoslang.`,`Qaroringizni boshqa o‘quvchiga qisqa va aniq tushuntiring.`]:[`Create a harder situation involving ${fallbackStrength?.subCompetency??"a demonstrated skill"}.`,`Compare two possible solutions using explicit criteria.`,`Explain and defend your decision to another student.`],resourceIds:[],practiceItemIds:fallbackStrength?[fallbackStrength.coreItemId]:[],successCheck:uz?"Yangi murakkab vaziyatda yechimni asoslab bera olish.":"Justify a solution in a new, more demanding situation."});
  if(priorityItems[1])weeks.push(targetedWeek(priorityItems[1],2,uz));else{const strength=strengthDiagnostics[1]??fallbackStrength;weeks.push({week:2,focus:uz?"Kuchli yo‘nalishlarni bog‘lash":"Connect demonstrated strengths",why:uz?"Bir nechta kuchli ko‘nikmani bitta amaliy vazifada qo‘llash tushunchani chuqurlashtiradi.":"Combining demonstrated skills in one practical task deepens understanding.",actions:uz?["Ikki kuchli ko‘nikmani talab qiladigan kichik vazifa tanlang.","Yechimni rejalashtiring, bajaring va natijani tekshirish mezonini yozing.","Jarayonda qilgan bitta taxminingizni sinab ko‘ring."]:["Choose a small task requiring two demonstrated skills.","Plan and complete it, then write a criterion for checking the result.","Identify and test one assumption made during the task."],resourceIds:[],practiceItemIds:strength?[strength.coreItemId]:[],successCheck:uz?"Ikki ko‘nikmani birlashtirib, tekshiriladigan natija yaratish.":"Combine two skills to produce a verifiable result."})}
  const applicationTargets=priorityItems.slice(0,2),applicationNames=applicationTargets.map(d=>d.subCompetency).join(" + ")||(fallbackStrength?.subCompetency??(uz?"amaliy tahlil":"practical analysis"));weeks.push({week:3,focus:uz?`Amaliy qo‘llash: ${applicationNames}`:`Application: ${applicationNames}`,why:uz?"Alohida mashq qilingan tushunchalarni realga yaqin vaziyatda birlashtirish dalilni mustahkamlaydi.":"Combining separately practised concepts in a realistic situation strengthens the evidence.",actions:uz?["Kundalik hayot yoki maktabdan mos muammoni tanlang.",`Yechimda ${applicationNames} dan foydalaning va har bir qadamni yozib boring.`,"Natijani kamida ikkita test holati bilan tekshiring."]:["Choose a relevant problem from school or daily life.",`Use ${applicationNames} in the solution and record each step.`,"Check the result with at least two test cases."],resourceIds:[],practiceItemIds:applicationTargets.map(d=>d.coreItemId),successCheck:uz?"Yechim ikki testdan o‘tishi va har bir qaror dalil bilan izohlanishi.":"The solution passes two tests and every decision is supported by evidence."});
  const retest=priorityItems.slice(0,3);weeks.push({week:4,focus:uz?"Mustahkamlash va qayta tekshirish":"Consolidation and reassessment",why:uz?"Aralash mashq vaqt o‘tib ham tushuncha saqlanganini va yangi vaziyatga ko‘chganini tekshiradi.":"Mixed practice checks whether learning is retained and transfers to a new context.",actions:uz?["Oldingi haftalardagi qaydlarni ko‘rmasdan uchta aralash vazifani bajaring.","Har bir javob uchun ishonch darajangizni yozing va keyin dalil bilan tekshiring.","Eng qiyin mavzu bo‘yicha yangi misol yarating va boshqa kishiga tushuntiring.","SkillMap’dagi ko‘rsatilgan mavzularni keyingi qayta baholash ro‘yxatiga kiriting."]:["Complete three mixed tasks without looking at earlier notes.","Record confidence for each answer, then verify it with evidence.","Create a new example for the hardest topic and teach it to someone else.","Add the referenced SkillMap topics to the next reassessment checklist."],resourceIds:[],practiceItemIds:retest.map(d=>d.coreItemId),successCheck:uz?"Uch aralash vazifadan kamida ikkitasini yordamsiz to‘g‘ri bajarish va yechimni izohlash.":"Complete at least two of three mixed tasks independently and explain the solutions."});
  return{summary:gaps.length?(uz?`Asosiy natija ${e.overallScore}%. Reja ${gaps.length} ta kuzatilgan rivojlanish signalidan eng muhimlarini ustuvor qiladi.`:`Common Core result: ${e.overallScore}%. The plan prioritizes the most important of ${gaps.length} observed development signals.`):(uz?`Asosiy natija ${e.overallScore}%. Ustuvor bo‘shliq kuzatilmadi; reja kuchli ko‘nikmalarni murakkabroq vazifalarda rivojlantiradi.`:`Common Core result: ${e.overallScore}%. No priority gap was observed; the plan advances demonstrated skills through harder applications.`),strengths:strengths.map(competency=>({competency,evidence:uz?"Asosiy topshiriqda to‘g‘ri yechim ko‘rsatildi.":"A correct solution was demonstrated on a Common Core item."})),priorities:priorityItems.map(d=>({competency:d.competency,reason:d.classification==="possible_weakness"?(uz?`${d.subCompetency} bo‘yicha javoblar mavzuni qayta ko‘rish foydali bo‘lishini ko‘rsatdi.`:`Responses suggest that reviewing ${d.subCompetency} would be useful.`):(uz?`${d.subCompetency} bo‘yicha qisman dalil bor; uni yangi misollarda mustahkamlash kerak.`:`There is partial evidence for ${d.subCompetency}; consolidate it with new examples.`),severity:d.classification==="possible_weakness"?"high":"medium"})),roadmap:weeks,questionsToWorkOn:priorityItems.map(d=>({competency:d.competency,prompt:uz?`${d.subCompetency} bo‘yicha qaroringizni qanday dalil bilan tekshirasiz?`:`What evidence would you use to verify a decision about ${d.subCompetency}?`})),insufficientEvidence:e.insufficientEvidence,confidenceNote:uz?`Dalil kuchi: ${e.evidenceStrength==="strong"?"yuqori":"o‘rtacha"}. Bu natija diagnostik signal bo‘lib, mutlaq hukm emas.`:`Evidence strength: ${e.evidenceStrength}. This is a diagnostic signal, not an absolute judgment.`}
}
export function validateGroundedRoadmap(value:unknown,e:V2EvidenceSummary){const parsed=roadmapSchema.parse(value),allowedCompetencies=new Set([...e.demonstratedStrengths,...e.developmentAreas]),allowedItems=new Set(e.attemptedItemIds);if([...parsed.strengths,...parsed.priorities,...parsed.questionsToWorkOn].some(x=>!allowedCompetencies.has(x.competency)))throw new Error("Roadmap contains an unmeasured competency");if(parsed.roadmap.some(w=>w.resourceIds.length||w.practiceItemIds.some(id=>!allowedItems.has(id))))throw new Error("Roadmap contains an unknown resource or item");return parsed}
export async function generateV2Roadmap(e:V2EvidenceSummary){const fallback=deterministicRoadmap(e),key=process.env.OPENAI_API_KEY;if(!key)return{roadmap:fallback,mode:"fallback"as const,provider:null,model:null};try{const model=process.env.OPENAI_MODEL||"gpt-5-mini",client=new OpenAI({apiKey:key,timeout:15_000,maxRetries:1}),response=await client.responses.parse({model,input:[{role:"system",content:`Create an evidence-grounded four-week SkillMap roadmap in ${e.locale}. Never diagnose untested skills. Use no external resources; resourceIds must be empty. practiceItemIds may only use attempted IDs.`},{role:"user",content:JSON.stringify(e)}],text:{format:zodTextFormat(roadmapSchema,"skillmap_roadmap")}});return{roadmap:validateGroundedRoadmap(response.output_parsed,e),mode:"ai"as const,provider:"openai",model}}catch(error){console.error("SkillMap roadmap fallback",{kind:error instanceof Error?error.name:"unknown"});return{roadmap:fallback,mode:"fallback"as const,provider:null,model:null}}
}
export function sanitizedEvidence(e:V2EvidenceSummary){return e}
