import type { Locale, SkillCategory } from "@/types/domain";

const en = {
  nav: { assessment: "Assessment", research: "Research dashboard", about: "About", signIn: "Sign in" },
  hero: { eyebrow: "Your digital skills map", title: "See what you do well. Know exactly what to learn next.", body: "Answer 24 practical questions and receive a clear skills result plus a personal 12-week learning plan.", primary: "Start assessment", secondary: "Explore research dashboard", note: "20–30 minutes · English or Uzbek · Your progress can be saved" },
  stats: ["6 skill domains", "24 practical questions", "12-week roadmap"],
  preview: { label:"Student skill map", title:"Diagnostic overview", level:"Developing", strengths:"4 strengths mapped" },
  measurementNote: "SkillMap measures applied judgment and reasoning — not memorization alone.",
  categoryCardMeta: "5 questions · Easy to hard · Applied scenarios",
  problem: { label: "The challenge", title: "Digital access is growing. Practical skill visibility is not.", body: "Grades and certificates rarely show whether a student can evaluate information, reason through a problem, read code, or stay safe online." },
  solution: { label: "The approach", title: "One diagnostic. Two useful outcomes.", student: "For every student", studentBody: "A clear skills profile and an actionable, deterministic learning roadmap.", system: "For the education system", systemBody: "Anonymous regional evidence to focus pilots, teacher support, and resources." },
  how: { label: "How it works", title: "From answers to your next task", steps: [["01", "Choose your goal", "Tell us your grade and what you want to learn."], ["02", "Answer 24 questions", "Work through practical situations, logic, and short code examples."], ["03", "Understand your result", "See three strengths and three areas to improve."], ["04", "Start your 12-week plan", "Open today's task, complete it, and track your progress."]] },
  categoriesTitle: "Six dimensions of practical digital capability",
  pilot: { label: "Pilot vision", title: "Built to inform action, not rank schools.", body: "SkillMap can support a responsible pilot across diverse regions and school types. Individual answers stay private; research views use anonymous, aggregated data.", points: ["Privacy-first data collection", "Comparable bilingual measurement", "Evidence for targeted intervention"] },
  faqTitle: "Common questions", faq: [["Is this an online course?", "It is a diagnostic and a 12-week guided learning system with linked daily tasks."], ["Does AI decide my score?", "No. Scoring is deterministic. AI may personalize weekly coaching, while approved tasks and links stay fixed."], ["Can I take it without an account?", "Yes, but an account is required to save roadmap task progress across devices."], ["How is research data protected?", "Dashboards use anonymous aggregates and suppress direct personal identifiers."]],
  cta: { title: "Make the next 30 days count.", body: "Take the diagnostic and leave with a learning plan you can start today.", button: "Begin assessment" },
  categories: { "digital-literacy": "Digital Literacy", "computational-thinking": "Computational Thinking", programming: "Programming Fundamentals", cybersecurity: "Cybersecurity", "ai-literacy": "AI Literacy", "problem-solving": "Problem Solving" } satisfies Record<SkillCategory,string>,
  results: { report:"Personal report",title:"Your digital skills map",subtitle:"Based on your practical diagnostic responses.",overall:"Overall score",coverage:"Diagnostic coverage",coverageHelp:"Average of completed items and competencies supported by at least two answers.",answered:"Answered",balance:"Category balance",correct:"correct",strongest:"Strongest category",priority:"Priority category",strongestCompetency:"Strongest competency",weakestCompetency:"Priority competency",misconceptions:"Patterns to revisit",reviewPattern:"Review this concept and practice it in a new example.",noMisconceptions:"No repeated misconception pattern was detected.",nextAction:"Next recommended action",insufficient:"Insufficient coverage",strong:"Strong",developing:"Developing",needsWork:"Needs work",foundation:"Foundation",proficient:"Proficient",advanced:"Advanced",limited:"Limited",partial:"Partial",good:"Good",roadmap:"12-week roadmap",learnNext:"What to learn next",week:"Week",goals:"Learning goals",practice:"Practice",project:"Mini project",milestone:"Milestone",print:"Print" },
};

const uz: typeof en = {
  nav: { assessment: "Baholash", research: "Tadqiqot paneli", about: "Loyiha haqida", signIn: "Kirish" },
  hero: { eyebrow: "Raqamli ko‘nikmalaringiz xaritasi", title: "Nimani yaxshi bilishingizni ko‘ring. Keyin nima o‘rganishni aniq biling.", body: "24 ta amaliy savolga javob bering. Kuchli tomonlaringiz, rivojlantiradigan yo‘nalishlaringiz va shaxsiy 12 haftalik rejangizni oling.", primary: "Baholashni boshlash", secondary: "Tadqiqot panelini ko‘rish", note: "20–30 daqiqa · O‘zbek yoki ingliz tili · Progressingizni saqlash mumkin" },
  stats: ["6 ko‘nikma yo‘nalishi", "24 amaliy savol", "12 haftalik yo‘l xaritasi"],
  preview: { label:"O‘quvchi ko‘nikmalari xaritasi", title:"Diagnostika sharhi", level:"Rivojlanmoqda", strengths:"4 ta kuchli tomon aniqlandi" },
  measurementNote: "SkillMap faqat yodlashni emas, amaliy fikrlash va mulohaza yuritishni o‘lchaydi.",
  categoryCardMeta: "5 savol · Osondan qiyingacha · Amaliy vaziyatlar",
  problem: { label: "Muammo", title: "Raqamli imkoniyatlar oshmoqda. Amaliy ko‘nikmalar esa ko‘rinmayapti.", body: "Baho va sertifikatlar o‘quvchi axborotni tekshira olishi, muammoni tahlil qilishi, kodni o‘qishi yoki internetda xavfsiz ishlashini har doim ham ko‘rsatmaydi." },
  solution: { label: "Yechim", title: "Bitta diagnostika. Ikki foydali natija.", student: "Har bir o‘quvchi uchun", studentBody: "Aniq ko‘nikmalar profili va tushunarli, qoidalarga asoslangan o‘quv rejasi.", system: "Ta’lim tizimi uchun", systemBody: "Pilotlar, o‘qituvchi yordami va resurslarni yo‘naltirish uchun anonim hududiy ma’lumot." },
  how: { label: "Qanday ishlaydi", title: "Javobdan bugungi vazifagacha", steps: [["01", "Maqsadingizni tanlang", "Sinfingiz va nimani o‘rganmoqchi ekaningizni ayting."], ["02", "24 savolga javob bering", "Amaliy vaziyatlar, mantiq va qisqa kod misollarini bajaring."], ["03", "Natijangizni tushuning", "Uchta kuchli va uchta rivojlantiradigan yo‘nalishni ko‘ring."], ["04", "12 haftalik rejani boshlang", "Bugungi vazifani oching, bajaring va progressingizni kuzating."]] },
  categoriesTitle: "Amaliy raqamli salohiyatning olti yo‘nalishi",
  pilot: { label: "Pilot maqsadi", title: "Maktablarni saralash uchun emas, harakatni yo‘naltirish uchun.", body: "SkillMap turli hudud va maktablarda mas’uliyatli pilotni qo‘llab-quvvatlaydi. Shaxsiy javoblar maxfiy, tadqiqot ko‘rinishlari esa anonim va umumlashtirilgan.", points: ["Maxfiylikka asoslangan ma’lumot", "Ikki tilda taqqoslanadigan o‘lchov", "Maqsadli yordam uchun dalil"] },
  faqTitle: "Ko‘p so‘raladigan savollar", faq: [["Bu onlayn kursmi?", "Bu diagnostika va havolali kundalik vazifalarga ega 12 haftalik o‘quv tizimi."], ["AI ballimni belgilaydimi?", "Yo‘q. Ball aniq qoidalar bilan hisoblanadi. AI haftalik murabbiy tavsiyasini moslashtiradi, tasdiqlangan vazifa va havolalar esa o‘zgarmaydi."], ["Hisobsiz qatnashsam bo‘ladimi?", "Ha, ammo roadmap progressini qurilmalar orasida saqlash uchun hisob kerak."], ["Tadqiqot ma’lumoti qanday himoyalanadi?", "Panel faqat anonim umumlashtirilgan ma’lumotdan foydalanadi."]],
  cta: { title: "Keyingi 30 kunni samarali o‘tkazing.", body: "Diagnostikadan o‘ting va bugunoq boshlash mumkin bo‘lgan rejani oling.", button: "Baholashni boshlash" },
  categories: { "digital-literacy": "Raqamli savodxonlik", "computational-thinking": "Hisoblash tafakkuri", programming: "Dasturlash asoslari", cybersecurity: "Kiberxavfsizlik", "ai-literacy": "SI savodxonligi", "problem-solving": "Muammo yechish" },
  results: { report:"Shaxsiy hisobot",title:"Raqamli ko‘nikmalar xaritasi",subtitle:"Natija amaliy diagnostika javoblaringizga asoslangan.",overall:"Umumiy ball",coverage:"Diagnostika qamrovi",coverageHelp:"Bajarilgan savollar va kamida ikki javob bilan tasdiqlangan ko‘nikmalar o‘rtachasi.",answered:"Javob berildi",balance:"Yo‘nalishlar balansi",correct:"to‘g‘ri",strongest:"Eng kuchli yo‘nalish",priority:"Ustuvor yo‘nalish",strongestCompetency:"Eng kuchli ko‘nikma",weakestCompetency:"Ustuvor ko‘nikma",misconceptions:"Qayta ko‘rib chiqiladigan tushunchalar",reviewPattern:"Bu tushunchani qayta ko‘rib chiqing va yangi misolda mashq qiling.",noMisconceptions:"Takrorlangan noto‘g‘ri tushuncha aniqlanmadi.",nextAction:"Keyingi tavsiya",insufficient:"Ma’lumot yetarli emas",strong:"Kuchli",developing:"Rivojlanmoqda",needsWork:"Mashq kerak",foundation:"Boshlang‘ich",proficient:"Malakali",advanced:"Yuqori",limited:"Cheklangan",partial:"Qisman",good:"Yaxshi",roadmap:"12 haftalik yo‘l xaritasi",learnNext:"Keyingi o‘rganish qadamlari",week:"Hafta",goals:"O‘rganish maqsadlari",practice:"Mashq",project:"Kichik loyiha",milestone:"Natija mezoni",print:"Chop etish" },
};
export type Dictionary = typeof en;
export function getDictionary(locale: Locale): Dictionary { return locale === "uz" ? uz : en; }
export function isLocale(value: string): value is Locale { return value === "en" || value === "uz"; }
