import type { Locale, SkillCategory } from "@/types/domain";

const en = {
  nav: { assessment: "Assessment", research: "Research dashboard", about: "About", signIn: "Sign in" },
  hero: { eyebrow: "National digital skills diagnostic", title: "See what students can do. Find what they need next.", body: "A practical, bilingual assessment that turns evidence into a focused 30-day learning plan — and anonymous insight for education leaders.", primary: "Start free assessment", secondary: "Explore research dashboard", note: "15–20 minutes · No account required · English or Uzbek" },
  stats: ["6 skill domains", "48 practical questions", "30-day roadmap"],
  preview: { label:"Student skill map", title:"Diagnostic overview", level:"Developing", strengths:"4 strengths mapped" },
  measurementNote: "SkillMap measures applied judgment and reasoning — not memorization alone.",
  categoryCardMeta: "8 questions · Easy to hard · Applied scenarios",
  problem: { label: "The challenge", title: "Digital access is growing. Practical skill visibility is not.", body: "Grades and certificates rarely show whether a student can evaluate information, reason through a problem, read code, or stay safe online." },
  solution: { label: "The approach", title: "One diagnostic. Two useful outcomes.", student: "For every student", studentBody: "A clear skills profile and an actionable, deterministic learning roadmap.", system: "For the education system", systemBody: "Anonymous regional evidence to focus pilots, teacher support, and resources." },
  how: { label: "How it works", title: "From answers to action", steps: [["01", "Tell us your context", "Grade, region, access, and experience help interpret results."], ["02", "Complete the diagnostic", "Answer practical scenarios, logic, code-reading, and knowledge questions."], ["03", "Receive your skill map", "See category scores, strengths, gaps, diagnostic coverage, and explanation."], ["04", "Follow a 30-day plan", "Build the weakest skills first through exercises and small projects."]] },
  categoriesTitle: "Six dimensions of practical digital capability",
  pilot: { label: "Pilot vision", title: "Built to inform action, not rank schools.", body: "SkillMap can support a responsible pilot across diverse regions and school types. Individual answers stay private; research views use anonymous, aggregated data.", points: ["Privacy-first data collection", "Comparable bilingual measurement", "Evidence for targeted intervention"] },
  faqTitle: "Common questions", faq: [["Is this an online course?", "No. SkillMap is a diagnostic and planning tool. It points students to what they should learn next."], ["Does it use AI to grade students?", "No. Scoring and roadmaps use transparent, deterministic rules."], ["Can I take it without an account?", "Yes. Guest mode is available for pilot testing."], ["How is research data protected?", "Dashboards use anonymous aggregates and suppress direct personal identifiers."]],
  cta: { title: "Make the next 30 days count.", body: "Take the diagnostic and leave with a learning plan you can start today.", button: "Begin assessment" },
  categories: { "digital-literacy": "Digital Literacy", "computational-thinking": "Computational Thinking", programming: "Programming Fundamentals", cybersecurity: "Cybersecurity", "ai-literacy": "AI Literacy", "problem-solving": "Problem Solving" } satisfies Record<SkillCategory,string>,
  results: { report:"Personal report",title:"Your digital skills map",subtitle:"Based on your practical diagnostic responses.",overall:"Overall score",coverage:"Diagnostic coverage",coverageHelp:"Average of completed items and competencies supported by at least two answers.",answered:"Answered",balance:"Category balance",correct:"correct",strongest:"Strongest category",priority:"Priority category",strongestCompetency:"Strongest competency",weakestCompetency:"Priority competency",misconceptions:"Patterns to revisit",reviewPattern:"Review this concept and practice it in a new example.",noMisconceptions:"No repeated misconception pattern was detected.",nextAction:"Next recommended action",insufficient:"Insufficient coverage",strong:"Strong",developing:"Developing",needsWork:"Needs work",foundation:"Foundation",proficient:"Proficient",advanced:"Advanced",limited:"Limited",partial:"Partial",good:"Good",roadmap:"30-day roadmap",learnNext:"What to learn next",week:"Week",goals:"Learning goals",practice:"Practice",project:"Mini project",milestone:"Milestone",print:"Print" },
};

const uz: typeof en = {
  nav: { assessment: "Baholash", research: "Tadqiqot paneli", about: "Loyiha haqida", signIn: "Kirish" },
  hero: { eyebrow: "Milliy raqamli ko‘nikmalar diagnostikasi", title: "O‘quvchi nimalarni bilishini ko‘ring. Keyingi qadamni aniqlang.", body: "Amaliy, ikki tilli baholash natijalarni aniq 30 kunlik o‘quv rejasiga, anonim ma’lumotlarni esa ta’lim uchun foydali tahlilga aylantiradi.", primary: "Bepul baholashni boshlash", secondary: "Tadqiqot panelini ko‘rish", note: "15–20 daqiqa · Hisob shart emas · O‘zbek yoki ingliz tili" },
  stats: ["6 ko‘nikma yo‘nalishi", "48 amaliy savol", "30 kunlik yo‘l xaritasi"],
  preview: { label:"O‘quvchi ko‘nikmalari xaritasi", title:"Diagnostika sharhi", level:"Rivojlanmoqda", strengths:"4 ta kuchli tomon aniqlandi" },
  measurementNote: "SkillMap faqat yodlashni emas, amaliy fikrlash va mulohaza yuritishni o‘lchaydi.",
  categoryCardMeta: "8 savol · Osondan qiyingacha · Amaliy vaziyatlar",
  problem: { label: "Muammo", title: "Raqamli imkoniyatlar oshmoqda. Amaliy ko‘nikmalar esa ko‘rinmayapti.", body: "Baho va sertifikatlar o‘quvchi axborotni tekshira olishi, muammoni tahlil qilishi, kodni o‘qishi yoki internetda xavfsiz ishlashini har doim ham ko‘rsatmaydi." },
  solution: { label: "Yechim", title: "Bitta diagnostika. Ikki foydali natija.", student: "Har bir o‘quvchi uchun", studentBody: "Aniq ko‘nikmalar profili va tushunarli, qoidalarga asoslangan o‘quv rejasi.", system: "Ta’lim tizimi uchun", systemBody: "Pilotlar, o‘qituvchi yordami va resurslarni yo‘naltirish uchun anonim hududiy ma’lumot." },
  how: { label: "Qanday ishlaydi", title: "Javobdan harakatgacha", steps: [["01", "O‘zingiz haqingizda ayting", "Sinf, hudud, imkoniyat va tajriba natijani to‘g‘ri talqin qilishga yordam beradi."], ["02", "Diagnostikani bajaring", "Vaziyatli, mantiqiy, kod o‘qish va bilim savollariga javob bering."], ["03", "Ko‘nikmalar xaritasini oling", "Ballar, kuchli tomonlar, bo‘shliqlar va izohlarni ko‘ring."], ["04", "30 kunlik rejaga amal qiling", "Mashqlar va kichik loyihalar bilan avval eng zaif ko‘nikmalarni rivojlantiring."]] },
  categoriesTitle: "Amaliy raqamli salohiyatning olti yo‘nalishi",
  pilot: { label: "Pilot maqsadi", title: "Maktablarni saralash uchun emas, harakatni yo‘naltirish uchun.", body: "SkillMap turli hudud va maktablarda mas’uliyatli pilotni qo‘llab-quvvatlaydi. Shaxsiy javoblar maxfiy, tadqiqot ko‘rinishlari esa anonim va umumlashtirilgan.", points: ["Maxfiylikka asoslangan ma’lumot", "Ikki tilda taqqoslanadigan o‘lchov", "Maqsadli yordam uchun dalil"] },
  faqTitle: "Ko‘p so‘raladigan savollar", faq: [["Bu onlayn kursmi?", "Yo‘q. SkillMap diagnostika va rejalashtirish vositasi bo‘lib, keyin nimani o‘rganishni ko‘rsatadi."], ["Baholashda sun’iy intellekt ishlatiladimi?", "Yo‘q. Ball va yo‘l xaritasi shaffof, oldindan belgilangan qoidalarga asoslanadi."], ["Hisobsiz qatnashsam bo‘ladimi?", "Ha. Pilot sinovi uchun mehmon rejimi mavjud."], ["Tadqiqot ma’lumoti qanday himoyalanadi?", "Panel faqat anonim umumlashtirilgan ma’lumotdan foydalanadi."]],
  cta: { title: "Keyingi 30 kunni samarali o‘tkazing.", body: "Diagnostikadan o‘ting va bugunoq boshlash mumkin bo‘lgan rejani oling.", button: "Baholashni boshlash" },
  categories: { "digital-literacy": "Raqamli savodxonlik", "computational-thinking": "Hisoblash tafakkuri", programming: "Dasturlash asoslari", cybersecurity: "Kiberxavfsizlik", "ai-literacy": "SI savodxonligi", "problem-solving": "Muammo yechish" },
  results: { report:"Shaxsiy hisobot",title:"Raqamli ko‘nikmalar xaritasi",subtitle:"Natija amaliy diagnostika javoblaringizga asoslangan.",overall:"Umumiy ball",coverage:"Diagnostika qamrovi",coverageHelp:"Bajarilgan savollar va kamida ikki javob bilan tasdiqlangan ko‘nikmalar o‘rtachasi.",answered:"Javob berildi",balance:"Yo‘nalishlar balansi",correct:"to‘g‘ri",strongest:"Eng kuchli yo‘nalish",priority:"Ustuvor yo‘nalish",strongestCompetency:"Eng kuchli ko‘nikma",weakestCompetency:"Ustuvor ko‘nikma",misconceptions:"Qayta ko‘rib chiqiladigan tushunchalar",reviewPattern:"Bu tushunchani qayta ko‘rib chiqing va yangi misolda mashq qiling.",noMisconceptions:"Takrorlangan noto‘g‘ri tushuncha aniqlanmadi.",nextAction:"Keyingi tavsiya",insufficient:"Ma’lumot yetarli emas",strong:"Kuchli",developing:"Rivojlanmoqda",needsWork:"Mashq kerak",foundation:"Boshlang‘ich",proficient:"Malakali",advanced:"Yuqori",limited:"Cheklangan",partial:"Qisman",good:"Yaxshi",roadmap:"30 kunlik yo‘l xaritasi",learnNext:"Keyingi o‘rganish qadamlari",week:"Hafta",goals:"O‘rganish maqsadlari",practice:"Mashq",project:"Kichik loyiha",milestone:"Natija mezoni",print:"Chop etish" },
};
export type Dictionary = typeof en;
export function getDictionary(locale: Locale): Dictionary { return locale === "uz" ? uz : en; }
export function isLocale(value: string): value is Locale { return value === "en" || value === "uz"; }
