import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, ChevronDown, ClipboardCheck, Eye, GraduationCap, LockKeyhole, MapPinned, Route, ShieldCheck, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { categories, categoryMeta } from "@/constants/app";
import { getDictionary,isLocale } from "@/lib/i18n/dictionaries";
const icons=[Eye,BrainCircuit,ClipboardCheck,ShieldCheck,Sparkles,Route];
export default async function Landing({params}:{params:Promise<{locale:string}>}) { const {locale}=await params;if(!isLocale(locale))notFound();const d=getDictionary(locale);return <>
  <section className="relative overflow-hidden border-b border-slate-200 bg-cream"><div className="absolute inset-0 grid-paper opacity-70"/><div className="container-shell relative grid min-h-[720px] items-center gap-14 py-20 lg:grid-cols-[1.08fr_.92fr]"><div><Badge>{d.hero.eyebrow}</Badge><h1 className="display mt-7 max-w-3xl text-5xl font-semibold leading-[1.02] text-ink sm:text-6xl lg:text-7xl">{d.hero.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">{d.hero.body}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href={`/${locale}/assessment`} className="group">{d.hero.primary}<ArrowRight size={17} className="transition group-hover:translate-x-1"/></ButtonLink><ButtonLink href={`/${locale}/research`} variant="secondary">{d.hero.secondary}</ButtonLink></div><p className="mt-5 text-sm text-slate-500">{d.hero.note}</p></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-8 rounded-full bg-teal-200/25 blur-3xl"/><Card className="relative overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{d.preview.label}</p><p className="mt-1 font-bold text-ink">{d.preview.title}</p></div><span className="grid size-12 place-items-center rounded-full bg-teal-50 font-serif text-xl font-bold text-teal-800">68</span></div><div className="p-6"><div className="mx-auto grid aspect-square max-w-64 place-items-center rounded-full border border-teal-100 bg-[radial-gradient(circle,#d7eee9_0_2px,transparent_2px)] [background-size:18px_18px]"><div className="grid size-40 place-items-center rounded-[36%_64%_58%_42%/46%_38%_62%_54%] bg-teal-800/90 text-center text-white shadow-xl"><div><BarChart3 className="mx-auto mb-2"/><strong className="text-2xl">{d.preview.level}</strong><p className="text-xs text-teal-100">{d.preview.strengths}</p></div></div></div><div className="mt-6 grid grid-cols-3 gap-2">{d.stats.map((s,i)=><div key={s} className="rounded-xl bg-slate-50 p-3 text-center"><strong className="block text-lg text-teal-800">{["6","48","30"][i]}</strong><span className="text-[11px] leading-tight text-slate-500">{s.replace(/^\d+\s*/,"")}</span></div>)}</div></div></Card></div></div></section>
  <section id="about" className="section bg-white"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:gap-24"><div><Badge>{d.problem.label}</Badge><h2 className="display mt-6 text-4xl font-semibold text-ink sm:text-5xl">{d.problem.title}</h2></div><div className="border-l-2 border-teal-700 pl-7"><p className="text-xl leading-9 text-slate-600">{d.problem.body}</p><div className="mt-8 flex items-start gap-3 rounded-xl bg-amber-50 p-5 text-sm leading-6 text-amber-950"><Eye className="mt-1 shrink-0" size={20}/><span>{d.measurementNote}</span></div></div></div></section>
  <section className="section bg-slate-950 text-white"><div className="container-shell"><Badge>{d.solution.label}</Badge><h2 className="display mt-6 text-4xl font-semibold sm:text-5xl">{d.solution.title}</h2><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-white/10 md:grid-cols-2"><div className="bg-slate-950 p-8 sm:p-11"><GraduationCap className="text-teal-300" size={32}/><h3 className="mt-8 text-2xl font-bold">{d.solution.student}</h3><p className="mt-3 max-w-lg leading-7 text-slate-300">{d.solution.studentBody}</p></div><div className="bg-slate-950 p-8 sm:p-11"><MapPinned className="text-teal-300" size={32}/><h3 className="mt-8 text-2xl font-bold">{d.solution.system}</h3><p className="mt-3 max-w-lg leading-7 text-slate-300">{d.solution.systemBody}</p></div></div></div></section>
  <section className="section"><div className="container-shell"><Badge>{d.how.label}</Badge><h2 className="display mt-6 text-4xl font-semibold text-ink sm:text-5xl">{d.how.title}</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{d.how.steps.map(([n,t,b])=><div key={n} className="border-t-2 border-teal-700 pt-5"><span className="font-serif text-3xl text-teal-700">{n}</span><h3 className="mt-7 font-bold text-ink">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{b}</p></div>)}</div></div></section>
  <section className="section border-y border-slate-200 bg-white"><div className="container-shell"><h2 className="display max-w-3xl text-4xl font-semibold text-ink sm:text-5xl">{d.categoriesTitle}</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((c,i)=>{const Icon=icons[i];return <Card key={c} className="group transition hover:-translate-y-1 hover:border-teal-300"><span className="grid size-11 place-items-center rounded-xl text-white" style={{background:categoryMeta[c].color}}><Icon size={21}/></span><h3 className="mt-7 text-lg font-bold text-ink">{d.categories[c]}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d.categoryCardMeta}</p></Card>})}</div></div></section>
  <section className="section bg-[#e6f1ed]"><div className="container-shell grid items-center gap-12 lg:grid-cols-[1fr_.8fr]"><div><Badge>{d.pilot.label}</Badge><h2 className="display mt-6 text-4xl font-semibold text-ink sm:text-5xl">{d.pilot.title}</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{d.pilot.body}</p></div><Card>{d.pilot.points.map(p=><div className="flex gap-3 border-b border-slate-100 py-4 last:border-0" key={p}><CheckCircle2 className="shrink-0 text-teal-700"/><span className="font-semibold">{p}</span></div>)}</Card></div></section>
  <section className="section bg-white"><div className="container-shell max-w-4xl"><h2 className="display text-center text-4xl font-semibold text-ink sm:text-5xl">{d.faqTitle}</h2><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{d.faq.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-ink">{q}<ChevronDown className="transition group-open:rotate-180"/></summary><p className="max-w-2xl pt-4 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>
  <section className="section bg-teal-900 text-white"><div className="container-shell text-center"><LockKeyhole className="mx-auto text-teal-300"/><h2 className="display mx-auto mt-6 max-w-3xl text-4xl font-semibold sm:text-5xl">{d.cta.title}</h2><p className="mx-auto mt-5 max-w-xl text-teal-100">{d.cta.body}</p><ButtonLink href={`/${locale}/assessment`} className="mt-8 bg-white text-teal-900 hover:bg-teal-50">{d.cta.button}<ArrowRight size={17}/></ButtonLink></div></section>
  </> }
