import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/dictionaries";

export default async function Privacy({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const uz = locale === "uz";
  return <div className="container-shell py-12 sm:py-16"><article className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-widest text-teal-700">{uz?"Maxfiylik":"Privacy"}</p><h1 className="display mt-3 text-4xl font-semibold sm:text-5xl">{uz?"Ma’lumotlarni himoyalash":"Data protection by design"}</h1><div className="mt-8 space-y-6 leading-7 text-slate-700">
    <p>{uz?"SkillMap natijalarni talqin qilish uchun zarur bo‘lgan cheklangan kontekst ma’lumotlarini yig‘adi. Ism, telefon, pasport yoki aniq manzil so‘ralmaydi.":"SkillMap collects limited context needed to interpret results. It does not ask for a name, phone number, passport details, or exact address."}</p>
    <h2 className="text-xl font-bold text-ink">{uz?"Baholash javoblari":"Assessment responses"}</h2><p>{uz?"Baholash yuborilganda ishtirokchi konteksti, savol javoblari, javob vaqtlari va hisoblangan natijalar pilot ma’lumotlar bazasida saqlanadi. Xom individual javoblar ommaga ochiq emas; ulardan faqat vakolatli pilot administratorlari foydalanishi mumkin.":"When an assessment is submitted, participant context, item responses, response timing, and calculated results are stored in the pilot database. Raw individual responses are not public and are available only to authorized pilot administrators."}</p>
    <h2 className="text-xl font-bold text-ink">{uz?"Tadqiqot hisobotlari":"Research reporting"}</h2><p>{uz?"Ochiq tadqiqot ko‘rinishlari faqat anonimlashtirilgan, umumlashtirilgan natijalarni ko‘rsatadi. Kichik guruhlar minimal hisobot chegarasiga yetmaguncha ko‘rsatilmaydi. Pilot natijalari O‘zbekistonning barcha o‘quvchilarini ifodalamaydi.":"Public research views show only anonymized, aggregated results. Small groups are withheld until they meet the minimum reporting threshold. Pilot findings are not representative of all students in Uzbekistan."}</p>
    <h2 className="text-xl font-bold text-ink">{uz?"Hisoblar va kirish nazorati":"Accounts and access control"}</h2><p>{uz?"Hisob ma’lumotlari Supabase Auth orqali boshqariladi. Qator darajasidagi xavfsizlik siyosatlari va rolga asoslangan administrator ruxsatlari batafsil yozuvlarga kirishni cheklaydi.":"Account credentials are handled by Supabase Auth. Row-level security policies and role-based admin permissions restrict access to detailed records."}</p>
    <h2 className="text-xl font-bold text-ink">{uz?"Pilot doirasi":"Pilot scope"}</h2><p>{uz?"Ishtirok ixtiyoriy. Bu rasmiy davlat imtihoni, milliy baholash yoki huquqiy muvofiqlik sertifikati emas. Saqlash muddati va ishtirokchi so‘rovlari pilot tashkilotchisi bilan kelishilgan tartibda boshqariladi.":"Participation is voluntary. This is not an official government exam, national validation study, or legal-compliance certification. Retention periods and participant requests are managed under the process agreed with the pilot organizer."}</p>
  </div></article></div>;
}
