/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase nested relation rows are untyped until generated database types are added. */
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2 } from "lucide-react";
import { getAdminOverview } from "@/lib/admin-data";
import { isLocale } from "@/lib/i18n/dictionaries";
import { notFound } from "next/navigation";

const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(new Date(value)):"Not set";
export default async function AdminOverview({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const data=await getAdminOverview(),uz=locale==="uz",warnings=[data.needsReview?`${data.needsReview} ${uz?"savol ko‘rib chiqilishi kerak":"questions need review"}`:null,data.doNotPublish?`${data.doNotPublish} ${uz?"savol nashr etilmaydi":"questions are blocked from publication"}`:null,!data.researchSufficient?`${uz?"Tadqiqot uchun yetarli yakunlangan urinish yo‘q":"Insufficient completed attempts for research reporting"}`:null,!data.settings.pilot_start_date||!data.settings.pilot_end_date?(uz?"Pilot sanalari to‘liq belgilanmagan":"Pilot date range is incomplete"):null].filter(Boolean);
const cards=[[uz?"Ishtirokchilar":"Participants",data.participants],[uz?"Yakunlangan urinishlar":"Completed attempts",data.completed],[uz?"Yakunlash darajasi":"Completion rate",`${data.completionRate}%`],[uz?"Nashrdagi savollar":"Published questions",data.published],["needs_review",data.needsReview],["do_not_publish",data.doNotPublish],[uz?"Fikr-mulohaza rejimi":"Feedback mode",data.settings.feedback_mode],[uz?"Minimal tadqiqot guruhi":"Minimum research group",data.settings.minimum_group_size]];
return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{uz?"Pilot operatsiyalari":"Pilot operations"}</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{uz?"Umumiy ko‘rinish":"Overview"}</h1><p className="mt-1 text-sm text-slate-600">{data.settings.pilot_name}</p></div><div className="text-sm text-slate-600">{date(data.settings.pilot_start_date)} — {date(data.settings.pilot_end_date)}</div></div>
<div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><section key={String(label)} className="rounded-lg border border-slate-300 bg-white p-4"><p className="text-xs font-semibold text-slate-600">{label}</p><strong className="mt-2 block text-2xl font-bold text-slate-950">{value}</strong></section>)}</div>
<div className="mt-6 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><section className="overflow-hidden rounded-lg border border-slate-300 bg-white"><div className="flex items-center justify-between border-b border-slate-300 px-4 py-3"><h2 className="font-bold">{uz?"So‘nggi urinishlar":"Recent attempts"}</h2><Link href={`/${locale}/admin/participants`} className="flex items-center gap-1 text-sm font-semibold text-teal-800">{uz?"Barchasi":"View all"}<ArrowRight size={15}/></Link></div>{data.recent.length?<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-600"><tr><th className="px-4 py-3">{uz?"Kod":"Code"}</th><th>{uz?"Hudud":"Region"}</th><th>{uz?"Holat":"Status"}</th><th>{uz?"Ball":"Score"}</th><th>{uz?"Boshlangan":"Started"}</th></tr></thead><tbody className="divide-y divide-slate-200">{data.recent.map((row:any)=><tr key={row.id}><td className="px-4 py-3 font-mono text-xs">{row.pilot_participants?.participant_code??"—"}</td><td>{row.pilot_participants?.region??"—"}</td><td>{row.status}</td><td>{row.overall_score??"—"}</td><td>{date(row.started_at)}</td></tr>)}</tbody></table></div>:<p className="p-6 text-sm text-slate-600">{uz?"Hali urinishlar yo‘q.":"No attempts yet."}</p>}</section>
<div className="space-y-5"><section className="rounded-lg border border-slate-300 bg-white"><div className="border-b border-slate-300 px-4 py-3"><h2 className="font-bold">{uz?"Pilot tayyorligi":"Pilot readiness"}</h2></div><div className="space-y-3 p-4">{warnings.length?warnings.map(item=><div key={item} className="flex gap-2 text-sm text-amber-900"><AlertTriangle className="mt-0.5 shrink-0" size={17}/><span>{item}</span></div>):<div className="flex gap-2 text-sm text-emerald-800"><CheckCircle2 size={17}/>{uz?"Faol ogohlantirish yo‘q":"No active warnings"}</div>}</div></section><section className="rounded-lg border border-slate-300 bg-white p-4"><h2 className="font-bold">{uz?"Tadqiqot holati":"Research status"}</h2><p className={`mt-3 text-sm font-semibold ${data.researchSufficient?"text-emerald-800":"text-amber-900"}`}>{data.researchSufficient?(uz?"Hisobot uchun yetarli":"Sufficient for reporting"):(uz?"Ma’lumot yetarli emas":"Insufficient data")}</p><p className="mt-1 text-xs text-slate-600">{data.completed} / {data.settings.minimum_group_size} {uz?"yakunlangan urinish":"completed attempts required"}</p></section></div></div></div>}
