"use client";

import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ArrowLeft, ArrowRight, Eye, EyeOff, KeyRound, LockKeyhole, Mail } from "lucide-react";
import { authSchema } from "@/validation/schemas";
import { resendSignupOtpAction, signInAction, signUpAction, verifySignupOtpAction } from "@/actions/auth";
import type { Locale } from "@/types/domain";
import { Button, buttonClass } from "@/components/ui/button";

type Values=z.infer<typeof authSchema>;

export function AuthForm({locale,mode}:{locale:Locale;mode:"sign-in"|"sign-up"}){
  const uz=locale==="uz",[show,setShow]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState(false),[verificationEmail,setVerificationEmail]=useState<string|null>(null),[token,setToken]=useState(""),[resendSeconds,setResendSeconds]=useState(0);
  const {register,handleSubmit,reset,formState:{errors}}=useForm<Values>({resolver:zodResolver(authSchema)});
  useEffect(()=>{if(resendSeconds<=0)return;const timer=setTimeout(()=>setResendSeconds(value=>value-1),1000);return()=>clearTimeout(timer)},[resendSeconds]);
  const inputClass="min-h-11 w-full rounded-lg border border-strong-border bg-white pl-10 pr-10 text-primary-text placeholder:text-muted-text focus:border-teal-800 focus:ring-2 focus:ring-teal-200";

  async function submit(values:Values){setPending(true);setMessage("");const result=mode==="sign-in"?await signInAction(locale,values):await signUpAction(locale,values);if(result.next==="verify"){setVerificationEmail(values.email);setResendSeconds(60);setToken("");reset()}setMessage(result.message);setPending(false)}
  async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!verificationEmail||pending)return;setPending(true);setMessage("");const result=await verifySignupOtpAction(locale,{email:verificationEmail,token});setMessage(result.message);setPending(false)}
  async function resend(){if(!verificationEmail||pending||resendSeconds>0)return;setPending(true);setMessage("");const result=await resendSignupOtpAction(locale,{email:verificationEmail});if(result.ok)setResendSeconds(60);setMessage(result.message);setPending(false)}
  function changeEmail(){setVerificationEmail(null);setToken("");setMessage("");setResendSeconds(0);reset()}

  if(mode==="sign-up"&&verificationEmail)return <form onSubmit={verify} className="space-y-5"><div className="rounded-xl border border-teal-200 bg-teal-50 p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-white text-teal-800"><Mail size={19}/></span><div className="min-w-0"><p className="text-sm font-bold text-teal-950">{uz?"Emailingizni tasdiqlang":"Verify your email"}</p><p className="mt-1 break-all text-sm text-teal-900">{verificationEmail}</p></div></div></div><div><label className="text-sm font-bold" htmlFor="signup-code">{uz?"Tasdiqlash kodi":"Verification code"}</label><p id="signup-code-help" className="mt-1 text-xs leading-5 text-secondary-text">{uz?"Emailga yuborilgan 6–8 xonali kodni kiriting.":"Enter the 6–8 digit code sent to your email."}</p><div className="relative mt-2"><KeyRound size={17} className="pointer-events-none absolute left-3 top-3.5 text-slate-600"/><input id="signup-code" value={token} onChange={event=>setToken(event.target.value.replace(/\D/g,"").slice(0,8))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,8}" minLength={6} maxLength={8} required aria-describedby="signup-code-help" className={`${inputClass} font-mono text-lg tracking-[.24em]`} /></div></div>{message&&<p role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-medium text-amber-950">{message}</p>}<Button disabled={pending||token.length<6} aria-busy={pending} className="w-full">{pending?(uz?"Tekshirilmoqda…":"Verifying…"):(uz?"Kodni tasdiqlash":"Verify code")}<ArrowRight size={17}/></Button><div className="flex flex-col items-center justify-between gap-3 text-sm sm:flex-row"><button type="button" onClick={changeEmail} className="inline-flex min-h-10 items-center gap-2 rounded px-2 font-semibold text-teal-900 underline underline-offset-2"><ArrowLeft size={15}/>{uz?"Emailni o‘zgartirish":"Change email"}</button><button type="button" disabled={pending||resendSeconds>0} onClick={resend} className="min-h-10 rounded px-2 font-semibold text-teal-900 underline underline-offset-2 disabled:text-slate-500 disabled:no-underline">{resendSeconds>0?(uz?`Qayta yuborish: ${resendSeconds} soniya`:`Resend in ${resendSeconds}s`):(uz?"Kodni qayta yuborish":"Resend code")}</button></div></form>;

  return <form onSubmit={handleSubmit(submit)} className="space-y-5"><div><label className="text-sm font-bold" htmlFor="email">Email</label><div className="relative mt-2"><Mail size={17} className="pointer-events-none absolute left-3 top-3.5 text-slate-600"/><input id="email" type="email" autoComplete="email" aria-invalid={!!errors.email} className={inputClass} {...register("email")}/></div>{errors.email&&<p role="alert" className="mt-1 text-xs font-medium text-red-700">{uz?"To‘g‘ri email manzilini kiriting.":errors.email.message}</p>}</div><div><div className="flex flex-wrap justify-between gap-2"><label className="text-sm font-bold" htmlFor="password">{uz?"Parol":"Password"}</label>{mode==="sign-in"&&<Link className="text-xs font-bold text-teal-900 underline underline-offset-2" href={`/${locale}/forgot-password`}>{uz?"Unutdingizmi?":"Forgot password?"}</Link>}</div><div className="relative mt-2"><LockKeyhole size={17} className="pointer-events-none absolute left-3 top-3.5 text-slate-600"/><input id="password" type={show?"text":"password"} autoComplete={mode==="sign-up"?"new-password":"current-password"} aria-invalid={!!errors.password} className={inputClass} {...register("password")}/><button type="button" aria-label={show?(uz?"Parolni yashirish":"Hide password"):(uz?"Parolni ko‘rsatish":"Show password")} onClick={()=>setShow(value=>!value)} className="absolute right-1.5 top-1.5 grid size-8 place-items-center rounded text-slate-700 hover:bg-slate-100 hover:text-slate-950">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{errors.password&&<p role="alert" className="mt-1 text-xs font-medium text-red-700">{uz?"Parol kamida 8 belgidan iborat bo‘lishi kerak.":errors.password.message}</p>}</div>{message&&<p role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-medium text-amber-950">{message}</p>}<Button disabled={pending} aria-busy={pending} className="w-full">{pending?(uz?"Yuklanmoqda…":"Loading…"):mode==="sign-in"?(uz?"Kirish":"Sign in"):(uz?"Hisob yaratish":"Create account")}<ArrowRight size={17}/></Button><div className="relative text-center text-xs font-medium text-slate-600 before:absolute before:left-0 before:right-0 before:top-1/2 before:border-t before:border-slate-300"><span className="relative bg-white px-3">{uz?"yoki":"or"}</span></div><Link href={`/${locale}/assessment`} className={`${buttonClass("secondary")} w-full`}>{uz?"Mehmon sifatida davom etish":"Continue as guest"}</Link></form>;
}
