"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { assessmentItemSchema } from "@/validation/assessment";
import { canMutateQuestions } from "@/lib/admin-auth";
async function authorize(mutate=false){const client=await createSupabaseServerClient(),admin=createSupabaseAdminClient();if(!client||!admin)throw new Error("Supabase admin mode is not configured");const {data:{user}}=await client.auth.getUser();if(!user)throw new Error("Authentication required");const {data:membership}=await admin.from("admins").select("role").eq("user_id",user.id).single();if(!membership||(mutate&&!canMutateQuestions(membership.role)))throw new Error("Admin authorization required");return{admin,user,role:membership.role}}
const refresh=()=>{revalidatePath("/en/admin","layout");revalidatePath("/uz/admin","layout")};
export async function saveAssessmentItem(input:unknown){const item=assessmentItemSchema.parse(input),{admin,user}=await authorize(true),eligible=item.reviewStatus==="approved"&&item.publishable;const {error}=await admin.from("questions").upsert({stable_id:item.id,version:item.version,status:item.status==="active"&&eligible?"published":item.status==="archived"?"archived":"draft",review_status:item.reviewStatus,review_notes:item.reviewNotes,category:item.category,competency_code:item.competencyCode,competency_name:item.competencyName,question_type:item.type,difficulty:item.difficulty,estimated_time_seconds:item.estimatedTimeSeconds,prompt_en:item.prompt.en,prompt_uz:item.prompt.uz,learning_objective:item.learningObjective,roadmap_skill_mapping:item.roadmapSkillMapping,misconception_id:item.misconceptionId,misconception_description:item.misconceptionDescription,tags:item.tags,correct_answer:item.correctAnswer,explanation_en:item.explanation.en,explanation_uz:item.explanation.uz,distractor_analysis:item.distractorAnalysis,adaptive_metadata:item.adaptiveMetadata??{},publishable:eligible,created_by:user.id},{onConflict:"stable_id,version"});if(error)throw new Error(error.message);await admin.from("activity_logs").insert({actor_id:user.id,action:"question.save",entity_type:"question",entity_id:item.id,metadata:{version:item.version,status:item.status,reviewStatus:item.reviewStatus}});refresh();return{ok:true}}
export async function setQuestionReviewStatus(stableId:string,version:number,reviewStatus:"approved"|"needs_review"|"do_not_publish"){const {admin,user}=await authorize(true),publishable=reviewStatus==="approved";const {error}=await admin.from("questions").update({review_status:reviewStatus,publishable,status:publishable?"draft":"draft",updated_at:new Date().toISOString()}).eq("stable_id",stableId).eq("version",version);if(error)throw new Error(error.message);await admin.from("activity_logs").insert({actor_id:user.id,action:"question.review",entity_type:"question",entity_id:stableId,metadata:{version,reviewStatus}});refresh();return{ok:true}}
export async function setQuestionStatus(stableId:string,version:number,status:"draft"|"published"|"archived"){const {admin,user}=await authorize(true);if(status==="published"){const {data}=await admin.from("questions").select("review_status,publishable,question_type").eq("stable_id",stableId).eq("version",version).single();if(!data||data.review_status!=="approved"||!data.publishable||["matching","ranking"].includes(data.question_type))throw new Error("Only approved eligible items can be published")};const {error}=await admin.from("questions").update({status,updated_at:new Date().toISOString()}).eq("stable_id",stableId).eq("version",version);if(error)throw new Error(error.message);await admin.from("activity_logs").insert({actor_id:user.id,action:`question.${status}`,entity_type:"question",entity_id:stableId,metadata:{version}});refresh();return{ok:true}}
export async function updatePilotSettings(input:{pilotName:string;startDate:string|null;endDate:string|null;minimumGroupSize:number;feedbackMode:"diagnostic"|"research-safe"}){const {admin,user}=await authorize(true),pilotName=input.pilotName.trim();if(pilotName.length<3||pilotName.length>120)throw new Error("Pilot name must be 3–120 characters");if(input.minimumGroupSize<3||input.minimumGroupSize>50)throw new Error("Invalid minimum group size");if(input.startDate&&input.endDate&&input.startDate>input.endDate)throw new Error("Pilot end date cannot be before its start date");const {error}=await admin.from("pilot_settings").update({pilot_name:pilotName,pilot_start_date:input.startDate||null,pilot_end_date:input.endDate||null,minimum_group_size:input.minimumGroupSize,feedback_mode:input.feedbackMode,updated_by:user.id,updated_at:new Date().toISOString()}).eq("id",true);if(error)throw new Error(error.message);await admin.from("activity_logs").insert({actor_id:user.id,action:"pilot.settings.update",entity_type:"pilot_settings",entity_id:"default",metadata:{...input,pilotName}});refresh();return{ok:true}}
