"use server";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { authSchema,forgotSchema } from "@/validation/schemas";
export type ActionState={ok:boolean;message:string};
export async function signInAction(locale:string,input:unknown):Promise<ActionState>{const parsed=authSchema.safeParse(input);if(!parsed.success)return {ok:false,message:parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:"Supabase is not configured. Use guest mode for this pilot."};const {error}=await supabase.auth.signInWithPassword(parsed.data);if(error)return {ok:false,message:error.message};redirect(`/${locale}/assessment`)}
export async function signUpAction(locale:string,input:unknown):Promise<ActionState>{const parsed=authSchema.safeParse(input);if(!parsed.success)return {ok:false,message:parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:"Supabase is not configured. Use guest mode for this pilot."};const {error}=await supabase.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{emailRedirectTo:`${process.env.NEXT_PUBLIC_APP_URL||"http://localhost:3000"}/${locale}/auth/callback`}});return error?{ok:false,message:error.message}:{ok:true,message:"Check your email to confirm your account."}}
export async function forgotAction(input:unknown):Promise<ActionState>{const parsed=forgotSchema.safeParse(input);if(!parsed.success)return {ok:false,message:parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:"Supabase is not configured."};const {error}=await supabase.auth.resetPasswordForEmail(parsed.data.email);return error?{ok:false,message:error.message}:{ok:true,message:"Password reset instructions have been sent."}}
export async function signOutAction(locale:string){const supabase=await createSupabaseServerClient();await supabase?.auth.signOut();redirect(`/${locale}`)}
