"use server";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { authSchema,forgotSchema } from "@/validation/schemas";
export type ActionState={ok:boolean;message:string};
export async function signInAction(locale:string,input:unknown):Promise<ActionState>{const uz=locale==="uz",parsed=authSchema.safeParse(input);if(!parsed.success)return {ok:false,message:uz?"Email yoki parol formati noto‘g‘ri.":parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:uz?"Kirish xizmati sozlanmagan. Pilotda mehmon sifatida davom eting.":"Sign-in is not configured. Continue as a guest for this pilot."};const {error}=await supabase.auth.signInWithPassword(parsed.data);if(error)return {ok:false,message:uz?"Email yoki parol noto‘g‘ri.":error.message};redirect(`/${locale}/assessment`)}
export async function signUpAction(locale:string,input:unknown):Promise<ActionState>{const uz=locale==="uz",parsed=authSchema.safeParse(input);if(!parsed.success)return {ok:false,message:uz?"Email yoki parol formati noto‘g‘ri.":parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:uz?"Ro‘yxatdan o‘tish xizmati sozlanmagan. Pilotda mehmon sifatida davom eting.":"Registration is not configured. Continue as a guest for this pilot."};const {error}=await supabase.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{emailRedirectTo:`${process.env.NEXT_PUBLIC_APP_URL||"http://localhost:3000"}/${locale}/auth/callback`}});return error?{ok:false,message:uz?"Hisobni yaratib bo‘lmadi. Ma’lumotlarni tekshirib, qayta urinib ko‘ring.":error.message}:{ok:true,message:uz?"Hisobni tasdiqlash uchun emailingizni tekshiring.":"Check your email to confirm your account."}}
export async function forgotAction(locale:string,input:unknown):Promise<ActionState>{const uz=locale==="uz",parsed=forgotSchema.safeParse(input);if(!parsed.success)return {ok:false,message:uz?"To‘g‘ri email manzilini kiriting.":parsed.error.issues[0].message};const supabase=await createSupabaseServerClient();if(!supabase)return {ok:false,message:uz?"Parolni tiklash xizmati sozlanmagan.":"Password reset is not configured."};const {error}=await supabase.auth.resetPasswordForEmail(parsed.data.email);return error?{ok:false,message:uz?"Tiklash havolasini yuborib bo‘lmadi. Keyinroq qayta urinib ko‘ring.":error.message}:{ok:true,message:uz?"Parolni tiklash ko‘rsatmalari yuborildi.":"Password reset instructions have been sent."}}
export async function signOutAction(locale:string){const supabase=await createSupabaseServerClient();await supabase?.auth.signOut();redirect(`/${locale}`)}
